"use strict";
/* ===== «Adagios: el lenguaje común de la filosofía» (09-10, Bachillerato) — datos =====
   Repertorio de lemas y adagios clásicos al estilo de los cuadernos de lugares comunes del Renacimiento.
   Campos: id; la = lema en latín (o la forma con que circula); gr = original griego, si lo hay, y tr = su transliteración (convención del glosario); es = traducción;
   o = de dónde viene (obra y pasaje; «fórmula tradicional» cuando no es literal); er = número en los Adagia de
   Erasmo (solo cuando consta); sen = qué quiere decir; uso = cuándo usarlo; trampa = error frecuente;
   amb = ámbito (saber | realidad | etica | politica | humano); e = época de origen (ant | med | ren | mod),
   para el color; t = temas de Teoría (ids de theory.js; la vista solo enlaza los que existen en cada web);
   img y pie = imagen de dominio público (créditos en recursos/imagenes_museos/adagios/) y su pie; fit:"contain" = no recortar (portadas, grabados, planos).
   Vista: adagiosview.js. Solo Bachillerato (build_eso.js lo deja fuera). */
const ADAGIOS = [
{ id:"amicorum", img:"media/galeria_museo/adagios/amicorum.jpg", pie:"Pitágoras, en La escuela de Atenas de Rafael (1509-1511)", la:"Amicorum communia omnia", gr:"Κοινὰ τὰ τῶν φίλων", tr:"koiná ta ton phílon", es:"Entre amigos, todo es común.",
  o:"Proverbio pitagórico que recogen Platón (Fedro 279c; Leyes V, 739c) y Aristóteles (Ética a Nicómaco VIII, 9)", er:"I, i, 1",
  sen:"La amistad verdadera no lleva cuentas: lo que es de uno es del otro. Erasmo lo puso el primero de toda su colección y lo leyó también como el germen de una sociedad que comparte sus bienes.",
  uso:"Para hablar de la amistad en Aristóteles o de la propiedad común de los guardianes en la República de Platón.",
  amb:"etica", e:"ant", t:["hf-etica", "hf-politica", "fil-t5"] },
{ id:"nosce", img:"media/galeria_museo/adagios/nosce.jpg", pie:"La sacerdotisa de Delfos, de John Collier (1891)", la:"Nosce te ipsum", gr:"Γνῶθι σεαυτόν", tr:"gnóthi seautón", es:"Conócete a ti mismo.",
  o:"Inscripción del templo de Apolo en Delfos; Platón la comenta en Protágoras 343b y Cármides 164d", er:"I, vi, 95",
  sen:"En Delfos era una advertencia: recuerda que eres mortal y no un dios. Sócrates la convirtió en un programa: examinar la propia vida y saber lo que uno no sabe.",
  uso:"Para presentar a Sócrates o para empezar cualquier tema sobre el ser humano.",
  amb:"humano", e:"ant", t:["hf-sofistas", "hf-antropologia", "fil-t2", "hf-montaigne-ensayos"] },
{ id:"nequid", img:"media/galeria_museo/adagios/nequid.jpg", pie:"Paisaje con la caída de Ícaro, atribuido a Pieter Bruegel el Viejo (hacia 1560): Ícaro voló demasiado alto", la:"Ne quid nimis", gr:"Μηδὲν ἄγαν", tr:"medén ágan", es:"Nada en exceso.",
  o:"Otra de las inscripciones de Delfos; en latín, Terencio, La andriana 61", er:"I, vi, 96",
  sen:"La sabiduría griega desconfía de todo exceso. Es la raíz popular de la virtud como término medio entre dos vicios.",
  uso:"Para explicar el término medio de Aristóteles.",
  trampa:"Aristóteles no defiende la mediocridad: el término medio es lo mejor, un extremo de excelencia, y no se calcula con una regla, sino con la prudencia.",
  amb:"etica", e:"ant", t:["hf-etica", "fil-t5"] },
{ id:"festina", img:"media/galeria_museo/adagios/festina.jpg", pie:"El ancla y el delfín, marca del impresor Aldo Manucio (Moralia de Plutarco, Venecia, 1509)", fit:"contain", la:"Festina lente", gr:"Σπεῦδε βραδέως", tr:"speúde bradéos", es:"Apresúrate despacio.",
  o:"Suetonio, Vida de Augusto 25: el emperador lo repetía a menudo", er:"II, i, 1",
  sen:"Une dos virtudes que parecen opuestas: decisión y prudencia. El impresor Aldo Manucio lo hizo su emblema con un delfín (rapidez) enroscado en un ancla (firmeza), y Erasmo le dedicó uno de sus comentarios más largos.",
  uso:"Para hablar de la prudencia o del método: avanzar, pero con orden.",
  amb:"etica", e:"ant", t:["hf-modernidad", "fil-t5"] },
{ id:"sileni", img:"media/galeria_museo/adagios/sileni.jpg", pie:"Alcibíades recibe las enseñanzas de Sócrates, de François-André Vincent (1776)", la:"Sileni Alcibiadis", es:"Los silenos de Alcibíades.",
  o:"Platón, Banquete 215a-b: Alcibíades compara a Sócrates con las figuras de sileno que se abrían y tenían dentro imágenes de dioses", er:"III, iii, 1",
  sen:"Lo valioso suele tener un exterior feo o humilde, y lo que brilla por fuera puede estar vacío. Sócrates, feo y pobre, guardaba dentro la sabiduría.",
  uso:"Para distinguir entre apariencia y realidad, o para describir a Sócrates.",
  amb:"saber", e:"ant", t:["hf-sofistas", "hf-platon", "fil-t1"] },
{ id:"spartam", img:"media/galeria_museo/adagios/spartam.jpg", pie:"Jóvenes espartanos ejercitándose, de Edgar Degas (hacia 1860)", la:"Spartam nactus es, hanc orna", gr:"Σπάρταν ἔλαχες, κείναν κόσμει", tr:"Spártan élakhes, keínan kósmei", es:"Te ha tocado Esparta: adórnala.",
  o:"Verso de Eurípides (tragedia perdida Télefo); lo cita Cicerón en sus cartas a Ático (IV, 6)", er:"II, v, 1",
  sen:"Haz bien el papel que te ha tocado en vez de envidiar el de otro. Erasmo lo aplicó a los príncipes: que gobiernen bien su reino antes de soñar con conquistar otros.",
  uso:"Para la ética estoica (aceptar el papel que te toca) o para criticar las guerras de conquista.",
  amb:"etica", e:"ant", t:["hf-helenismo", "fil-helenismo"] },
{ id:"dulce", img:"media/galeria_museo/adagios/dulce.jpg", pie:"El triunfo de la muerte, de Pieter Bruegel el Viejo (hacia 1562)", la:"Dulce bellum inexpertis", es:"La guerra es dulce para quien no la ha probado.",
  o:"Píndaro (fragmento 110), en latín por Vegecio", er:"IV, i, 1",
  sen:"Solo ensalza la guerra quien no la conoce. Erasmo lo convirtió en un largo alegato contra la guerra entre cristianos, que se imprimió muchas veces como libro aparte.",
  uso:"Para hablar del pacifismo humanista o de la paz perpetua de Kant.",
  amb:"politica", e:"ant", t:["hf-modernidad", "hf-kant", "fil-t6"] },
{ id:"scarabeus", img:"media/galeria_museo/adagios/scarabeus.jpg", pie:"El águila y el escarabajo, grabado de Wenceslaus Hollar (siglo XVII)", fit:"contain", la:"Scarabeus aquilam quaerit", es:"El escarabajo persigue al águila.",
  o:"Fábula de Esopo: el escarabajo se venga del águila rompiéndole los huevos", er:"III, vii, 1",
  sen:"Ni el más débil es despreciable: también puede vengarse del poderoso. Erasmo lo usó para criticar a los reyes que se comportan como aves de rapiña.",
  uso:"Para hablar del poder y de sus límites.",
  amb:"politica", e:"ant", t:["hf-contrato", "fil-t6"] },
{ id:"autregem", img:"media/galeria_museo/adagios/autregem.jpg", pie:"El bufón Calabacillas, de Diego Velázquez (hacia 1636-1638)", la:"Aut regem aut fatuum nasci oportere", es:"Hay que nacer rey o tonto.",
  o:"Séneca, Apocolocyntosis 1 (sátira sobre la muerte del emperador Claudio)", er:"I, iii, 1",
  sen:"Solo a los reyes y a los bufones se les perdona todo. Erasmo aprovecha el adagio para escribir un pequeño tratado sobre cómo debe ser un buen príncipe.",
  uso:"Para hablar de la educación del gobernante (Platón, Erasmo, Maquiavelo).",
  amb:"politica", e:"ant", t:["hf-politica", "hf-contrato", "fil-t6"] },
{ id:"herculei", img:"media/galeria_museo/adagios/herculei.jpg", pie:"Hércules lucha con la hidra de Lerna, de Francisco de Zurbarán (1634)", la:"Herculei labores", es:"Trabajos de Hércules.",
  o:"Los doce trabajos del mito de Heracles", er:"III, i, 1",
  sen:"Una tarea enorme e ingrata. Erasmo lo usó para hablar de su propio trabajo: reunir y comentar miles de adagios le parecía un trabajo de Hércules.",
  uso:"Para hablar de proyectos enormes como la Enciclopedia o los Adagia.",
  amb:"humano", e:"ant", t:["hf-modernidad", "hf-ilustracion"] },
{ id:"lupus", img:"media/galeria_museo/adagios/lupus.jpg", pie:"Portada del Leviatán de Hobbes, grabada por Abraham Bosse (1651)", fit:"contain", la:"Homo homini lupus", es:"El hombre es un lobo para el hombre.",
  o:"Plauto, Asinaria 495, con las palabras en otro orden; Hobbes, De cive, carta dedicatoria (1642)", er:"I, i, 70",
  sen:"Entre desconocidos, sin ley que nos proteja, el otro es una amenaza. Hobbes la usa para describir el estado de naturaleza.",
  uso:"Para el estado de naturaleza y el contrato social.",
  trampa:"La frase no es de Hobbes, sino de Plauto, y en la misma carta Hobbes pone la contraria: «el hombre es un dios para el hombre» (entre ciudadanos que viven bajo leyes). En Plauto, además, la frase dice que el hombre es un lobo para quien no conoce.",
  amb:"politica", e:"ant", t:["hf-contrato", "fil-t6"] },
{ id:"zoon", img:"media/galeria_museo/adagios/zoon.jpg", pie:"Pericles pronuncia la oración fúnebre, estampa según Philipp Foltz (hacia 1875-1880)", la:"Animal politicum", gr:"Ζῷον πολιτικόν", tr:"zóon politikón", es:"El ser humano es un animal político.",
  o:"Aristóteles, Política I, 2, 1253a",
  sen:"El ser humano solo se realiza plenamente en la ciudad (polis), porque tiene palabra (logos) para discutir qué es justo. Quien puede vivir solo, dice Aristóteles, es una bestia o un dios.",
  uso:"Para la política clásica o para comparar con el contrato social.",
  trampa:"«Político» no quiere decir que nos guste la política de partidos, sino que somos seres de la polis: necesitamos la comunidad para vivir bien.",
  amb:"politica", e:"ant", t:["hf-politica", "hf-antropologia", "fil-t6", "fil-t2"] },
{ id:"pantarhei", img:"media/galeria_museo/adagios/pantarhei.jpg", pie:"Heráclito, de Johannes Moreelse (hacia 1630)", la:"Panta rhei", gr:"Πάντα ῥεῖ", tr:"pánta rhei", es:"Todo fluye.",
  o:"Fórmula tradicional atribuida a Heráclito; cf. Platón, Crátilo 402a: «todo se mueve y nada permanece»",
  sen:"La realidad es cambio continuo: no te puedes bañar dos veces en el mismo río.",
  uso:"Para los presocráticos y el problema del cambio.",
  trampa:"La fórmula exacta no aparece en ningún fragmento de Heráclito. Además, para él el cambio no es caos: sigue una medida, el logos, que mantiene unidos los contrarios.",
  amb:"realidad", e:"ant", t:["hf-preso", "fil-presocraticos"] },
{ id:"exnihilo", img:"media/galeria_museo/adagios/exnihilo.jpg", pie:"Separación de la luz y las tinieblas, de Miguel Ángel (Capilla Sixtina, 1511)", la:"Ex nihilo nihil fit", es:"De la nada, nada sale.",
  o:"Principio que recorre la filosofía griega desde Parménides; en latín, Lucrecio, De rerum natura I, 150-156",
  sen:"Todo lo que llega a ser procede de algo. Los griegos lo daban por evidente; la idea cristiana de creación «de la nada» (ex nihilo) chocó con él.",
  uso:"Para los presocráticos o para el debate entre fe y razón sobre la creación del mundo.",
  amb:"realidad", e:"ant", t:["hf-preso", "hf-fe-razon", "fil-presocraticos"] },
{ id:"mensura", img:"media/galeria_museo/adagios/mensura.jpg", pie:"Demócrito y Protágoras, de Salvator Rosa (hacia 1663-1664)", la:"Homo mensura", gr:"Πάντων χρημάτων μέτρον ἄνθρωπος", tr:"pánton khremáton métron ánthropos", es:"El hombre es la medida de todas las cosas.",
  o:"Protágoras, citado por Platón, Teeteto 152a",
  sen:"Las cosas son para cada uno tal como le aparecen: no hay una verdad que esté por encima de todos los puntos de vista.",
  uso:"Para los sofistas y el relativismo.",
  trampa:"No es un elogio del ser humano al estilo del Renacimiento, sino una tesis relativista: lo que a ti te parece verdad, es verdad para ti.",
  amb:"saber", e:"ant", t:["hf-sofistas", "fil-t3"] },
{ id:"solose", img:"media/galeria_museo/adagios/solose.jpg", pie:"La muerte de Sócrates, de Jacques-Louis David (1787)", la:"Scio me nihil scire", es:"Solo sé que no sé nada.",
  o:"Fórmula tradicional; cf. Platón, Apología 21d: «no creo saber lo que no sé»",
  sen:"El primer paso del saber es reconocer la propia ignorancia. El sabio no es el que lo sabe todo, sino el que sabe qué no sabe.",
  uso:"Para presentar la ironía socrática.",
  trampa:"Sócrates no dice que no sepa nada, que sería contradictorio, sino que no cree saber lo que no sabe. Es más sabio que los demás porque es consciente de sus límites.",
  amb:"saber", e:"ant", t:["hf-sofistas", "fil-t1"] },
{ id:"amicusplato", img:"media/galeria_museo/adagios/amicusplato.jpg", pie:"Platón y Aristóteles, en La escuela de Atenas de Rafael (1509-1511)", la:"Amicus Plato, sed magis amica veritas", es:"Platón es mi amigo, pero la verdad lo es más.",
  o:"Fórmula tradicional medieval; cf. Aristóteles, Ética a Nicómaco I, 6, 1096a",
  sen:"Antes que fiel a un maestro, hay que serlo a la verdad. Aristóteles lo dice al empezar su crítica de la Idea de Bien de Platón: es piadoso honrar la verdad antes que a los amigos.",
  uso:"Para la crítica de Aristóteles a Platón o para defender la libertad de pensar.",
  amb:"saber", e:"ant", t:["hf-platon", "hf-metodos", "fil-t1"] },
{ id:"tabula", img:"media/galeria_museo/adagios/tabula.jpg", pie:"Tablilla de cera con ejercicios escolares en griego (Egipto, siglo II; British Library)", fit:"contain", la:"Tabula rasa", es:"Tablilla en blanco.",
  o:"Aristóteles, Acerca del alma III, 4, 430a (la tablilla en que aún no hay nada escrito); Locke habla de un papel en blanco (Ensayo II, 1, 2)",
  sen:"La mente, al nacer, no trae ideas: todo lo escribe en ella la experiencia.",
  uso:"Para el empirismo y el debate sobre las ideas innatas.",
  amb:"saber", e:"ant", t:["hf-racionalismo", "fil-t3"] },
{ id:"nihilest", img:"media/galeria_museo/adagios/nihilest.jpg", pie:"La vista, de Jan Brueghel el Viejo y Rubens (1617; Museo del Prado)", la:"Nihil est in intellectu quod non prius fuerit in sensu", es:"No hay nada en el entendimiento que no haya estado antes en los sentidos.",
  o:"Axioma escolástico; Tomás de Aquino, De veritate q. 2, a. 3. Leibniz le añadió: «nisi ipse intellectus» («excepto el propio entendimiento»)",
  sen:"Todo conocimiento empieza por los sentidos. El empirismo lo hace suyo; Leibniz le pone una excepción decisiva: las estructuras de la propia mente.",
  uso:"Para el debate entre racionalismo y empirismo.",
  amb:"saber", e:"med", t:["hf-racionalismo", "hf-fe-razon", "fil-t3"] },
{ id:"credo", img:"media/galeria_museo/adagios/credo.jpg", pie:"San Agustín en su estudio, de Sandro Botticelli (hacia 1490-1494)", la:"Credo ut intelligam", es:"Creo para entender.",
  o:"Anselmo de Canterbury, Proslogion 1; antes, Agustín de Hipona: «crede ut intelligas» (Sermón 43)",
  sen:"La fe no sustituye a la razón: le abre el camino. Quien cree busca entender lo que cree.",
  uso:"Para las relaciones entre fe y razón en la Edad Media.",
  amb:"saber", e:"med", t:["hf-fe-razon", "hf-medieval"] },
{ id:"ockham", img:"media/galeria_museo/adagios/ockham.jpg", pie:"Ockham, dibujado al margen de un manuscrito de su Summa logicae (1341)", fit:"contain", la:"Entia non sunt multiplicanda praeter necessitatem", es:"No hay que multiplicar los entes sin necesidad.",
  o:"La «navaja de Ockham». Ockham escribe «pluralitas non est ponenda sine necessitate»; la fórmula famosa es de John Punch (1639)",
  sen:"Entre dos explicaciones, quédate con la que necesita menos supuestos. Ockham la usó para eliminar los universales como cosas reales.",
  uso:"Para el problema de los universales o para cualquier discusión sobre qué explicación es mejor.",
  trampa:"No dice que la explicación más simple sea siempre la verdadera, sino que no hay que añadir supuestos que no hacen falta.",
  amb:"saber", e:"med", t:["hf-medieval", "fil-t3", "fil-t4"] },
{ id:"scientia", img:"media/galeria_museo/adagios/scientia.jpg", pie:"Portada de la Instauratio magna de Francis Bacon (1620): una nave cruza las columnas de Hércules", fit:"contain", la:"Ipsa scientia potestas est", es:"El saber mismo es poder.",
  o:"Francis Bacon, Meditationes sacrae (1597); la idea vuelve en el Novum organum I, 3",
  sen:"Conocer las causas de la naturaleza permite dominarla. La ciencia moderna ya no busca solo contemplar, sino transformar el mundo.",
  uso:"Para la revolución científica o para la crítica de la razón instrumental.",
  amb:"saber", e:"ren", t:["hf-modernidad", "hf-capitalismo", "fil-t3"] },
{ id:"sapere", img:"media/galeria_museo/adagios/sapere.jpg", pie:"Comienzo de «¿Qué es la Ilustración?» de Kant en la Berlinische Monatsschrift (1784)", fit:"contain", la:"Sapere aude", es:"Atrévete a saber.",
  o:"Horacio, Epístolas I, 2, 40; Kant lo hace lema de la Ilustración en ¿Qué es la Ilustración? (1784)",
  sen:"Ten el valor de servirte de tu propio entendimiento, sin la guía de otro.",
  uso:"Para la Ilustración y Kant.",
  trampa:"No es de Kant: es un verso de Horacio, que hablaba de empezar a vivir bien sin aplazarlo. Kant lo reinterpreta como lema de la Ilustración.",
  amb:"saber", e:"ant", t:["hf-ilustracion", "hf-kant", "fil-t1"] },
{ id:"errare", img:"media/galeria_museo/adagios/errare.jpg", pie:"La parábola de los ciegos, de Pieter Bruegel el Viejo (1568)", la:"Errare humanum est", es:"Equivocarse es humano.",
  o:"Fórmula tradicional; cf. Cicerón, Filípicas XII, 5: «es propio de cualquiera equivocarse, y solo del necio perseverar en el error»",
  sen:"El error forma parte del conocimiento humano. Lo grave no es equivocarse, sino no corregirse.",
  uso:"Para el falibilismo o para el método científico.",
  amb:"saber", e:"ant", t:["fil-t3", "hf-metodos"] },
{ id:"carpe", img:"media/galeria_museo/adagios/carpe.jpg", pie:"Coged las rosas mientras podáis, de John William Waterhouse (1908)", la:"Carpe diem", es:"Aprovecha el día.",
  o:"Horacio, Odas I, 11, 8",
  sen:"No confíes en el mañana: vive bien el presente.",
  uso:"Para el epicureísmo.",
  trampa:"No significa «haz lo que te apetezca». Horacio es epicúreo: aprovechar el día es disfrutar con moderación de lo que hay, sin angustiarse por el futuro.",
  amb:"etica", e:"ant", t:["hf-helenismo", "fil-helenismo"] },
{ id:"latuit", img:"media/galeria_museo/adagios/latuit.jpg", pie:"Busto de Epicuro, copia romana (British Museum)", la:"Bene qui latuit, bene vixit", gr:"Λάθε βιώσας", tr:"láthe biósas", es:"Vivió bien quien vivió oculto.",
  o:"Ovidio, Tristes III, 4, 25; en griego, el lema de Epicuro «vive oculto»",
  sen:"La felicidad está lejos de la fama y la política, en una vida tranquila con los amigos.",
  uso:"Para el epicureísmo y el Jardín.",
  amb:"etica", e:"ant", t:["hf-helenismo", "fil-helenismo"] },
{ id:"sustine", img:"media/galeria_museo/adagios/sustine.jpg", pie:"Epicteto, grabado de Henri Bonnart (hacia 1700)", fit:"contain", la:"Sustine et abstine", gr:"Ἀνέχου καὶ ἀπέχου", tr:"anékhou kai apékhou", es:"Soporta y abstente.",
  o:"Epicteto, según Aulo Gelio, Noches áticas XVII, 19",
  sen:"Soporta lo que no depende de ti y abstente de lo que te esclaviza. Es el resumen estoico de la vida buena.",
  uso:"Para el estoicismo.",
  amb:"etica", e:"ant", t:["hf-helenismo", "fil-helenismo"] },
{ id:"memento", img:"media/galeria_museo/adagios/memento.jpg", pie:"Memento mori: mosaico de Pompeya con calavera y rueda de la fortuna (Museo Arqueológico de Nápoles)", la:"Memento mori", es:"Recuerda que vas a morir.",
  o:"Fórmula tradicional; Tertuliano, Apologético 33, cuenta que en los triunfos romanos se le recordaba al general: «mira detrás de ti; recuerda que eres un hombre»",
  sen:"Recordar la muerte no es para entristecerse, sino para poner las cosas en su sitio y no perder el tiempo en lo que no importa.",
  uso:"Para el estoicismo o el existencialismo (el ser para la muerte de Heidegger).",
  amb:"humano", e:"ant", t:["hf-helenismo", "hf-existencialismo", "fil-t2"] },
{ id:"vitabrevis", img:"media/galeria_museo/adagios/vitabrevis.jpg", pie:"Hipócrates, grabado de Paulus Pontius según Rubens (1638)", la:"Ars longa, vita brevis", gr:"Ὁ βίος βραχύς, ἡ δὲ τέχνη μακρή", tr:"ho bíos brakhýs, he de tékhne makré", es:"La vida es breve; el arte, largo.",
  o:"Hipócrates, Aforismos I, 1; Séneca lo recuerda al empezar Sobre la brevedad de la vida",
  sen:"En Hipócrates, el «arte» es la medicina: hace falta mucho tiempo para dominarla y la vida no alcanza. Séneca responde que la vida no es breve, sino que la desperdiciamos.",
  uso:"Para hablar del tiempo y del uso de la vida (Séneca).",
  amb:"humano", e:"ant", t:["hf-helenismo", "fil-helenismo"] },
{ id:"homosum", img:"media/galeria_museo/adagios/homosum.jpg", pie:"Actores con máscaras en un manuscrito de las comedias de Terencio (siglo IX; Biblioteca Vaticana)", la:"Homo sum, humani nihil a me alienum puto", es:"Soy hombre, y nada de lo humano me es ajeno.",
  o:"Terencio, El atormentador de sí mismo 77",
  sen:"Todo lo que le pasa a cualquier ser humano me concierne. El humanismo del Renacimiento lo leyó como un programa de curiosidad y solidaridad.",
  uso:"Para el humanismo o para el cosmopolitismo.",
  trampa:"En la comedia lo dice un vecino entrometido para justificar que se mete en la vida de otro.",
  amb:"humano", e:"ant", t:["hf-modernidad", "fil-t2"] },
{ id:"ubibene", img:"media/galeria_museo/adagios/ubibene.jpg", pie:"Diógenes, de Jean-Léon Gérôme (1860)", la:"Ubi bene, ibi patria", es:"Donde se está bien, allí está la patria.",
  o:"Cicerón, Tusculanas V, 108, citando un verso de Pacuvio",
  sen:"La patria no es el lugar donde se nace, sino donde se puede vivir bien. Es una idea cosmopolita, cercana a los cínicos y a los estoicos.",
  uso:"Para el cosmopolitismo helenístico o para debatir sobre la identidad.",
  amb:"politica", e:"ant", t:["hf-helenismo", "fil-t6"] },
{ id:"mens", img:"media/galeria_museo/adagios/mens.jpg", pie:"Juvenal coronado de laurel (grabado)", fit:"contain", la:"Mens sana in corpore sano", es:"Mente sana en cuerpo sano.",
  o:"Juvenal, Sátiras X, 356, al final de una sátira sobre lo que la gente pide a los dioses",
  sen:"En Juvenal es una oración: lo único que vale la pena pedir a los dioses es una mente sana en un cuerpo sano, y no riquezas, poder o belleza.",
  uso:"Para hablar de la relación entre cuerpo y alma.",
  trampa:"No es un lema deportivo. Juvenal se burla de lo que la gente pide a los dioses y propone pedir solo lo que de verdad importa.",
  amb:"humano", e:"ant", t:["fil-t2", "hf-antropologia"] },
{ id:"panem", img:"media/galeria_museo/adagios/panem.jpg", pie:"Pollice verso, de Jean-Léon Gérôme (1872)", la:"Panem et circenses", es:"Pan y circo.",
  o:"Juvenal, Sátiras X, 81",
  sen:"El pueblo romano, que antes repartía cargos y legiones, ya solo desea dos cosas: pan y juegos. El poder lo tiene contento con comida y espectáculos.",
  uso:"Para hablar de la manipulación política o de la sociedad del espectáculo.",
  amb:"politica", e:"ant", t:["fil-t6", "hf-siglo21"] },
{ id:"custodes", img:"media/galeria_museo/adagios/custodes.jpg", pie:"El panóptico de Jeremy Bentham (1843): una cárcel en la que un solo vigilante puede verlo todo", fit:"contain", la:"Quis custodiet ipsos custodes?", es:"¿Quién vigilará a los propios vigilantes?",
  o:"Juvenal, Sátiras VI, 347-348",
  sen:"Si alguien tiene que vigilar, ¿quién lo vigila a él? Es la gran pregunta del control del poder.",
  uso:"Para los guardianes de la República de Platón o para la división de poderes.",
  trampa:"En Juvenal no habla de política: se burla de los maridos que ponen guardianes a sus esposas, porque las esposas pueden empezar por los guardianes.",
  amb:"politica", e:"ant", t:["hf-politica", "hf-contrato", "fil-t6"] },
{ id:"duralex", img:"media/galeria_museo/adagios/duralex.jpg", pie:"Antígona ante el cadáver de Polinices, de Nikiforos Lytras (1865)", la:"Dura lex, sed lex", es:"La ley es dura, pero es la ley.",
  o:"Fórmula tradicional; cf. el jurista Ulpiano en el Digesto 40, 9, 12: «es muy duro, pero así está escrita la ley»",
  sen:"La ley obliga aunque nos parezca dura en un caso concreto.",
  uso:"Para el debate entre ley y justicia (Antígona, Sócrates en el Critón).",
  amb:"politica", e:"ant", t:["fil-t6", "fil-t5", "hf-sofistas"] },
{ id:"fiat", img:"media/galeria_museo/adagios/fiat.jpg", pie:"Alegoría de la Justicia, de Giorgio Vasari (1543)", la:"Fiat iustitia, pereat mundus", es:"Hágase justicia, aunque perezca el mundo.",
  o:"Lema del emperador Fernando I (siglo XVI); Kant lo discute en Sobre la paz perpetua (1795), apéndice I",
  sen:"La justicia no se negocia por sus consecuencias. Kant lo traduce así: que se haga justicia aunque perezcan todos los bribones del mundo.",
  uso:"Para la ética del deber frente al utilitarismo.",
  amb:"etica", e:"ren", t:["hf-etica-deber", "hf-kant", "fil-t5"] },
{ id:"fortes", img:"media/galeria_museo/adagios/fortes.jpg", pie:"Némesis o la Gran Fortuna, grabado de Alberto Durero (hacia 1501-1502)", la:"Fortes fortuna adiuvat", es:"La fortuna ayuda a los audaces.",
  o:"Terencio, Formión 203; Maquiavelo lo reelabora en El príncipe XXV",
  sen:"La suerte favorece a quien se atreve. Para Maquiavelo, la fortuna gobierna la mitad de nuestras acciones, y la otra mitad depende de la virtù del gobernante.",
  uso:"Para Maquiavelo: virtù y fortuna.",
  amb:"politica", e:"ant", t:["hf-contrato", "hf-modernidad", "fil-t6"] },
{ id:"cuius", img:"media/galeria_museo/adagios/cuius.jpg", pie:"Documento de la Paz de Augsburgo (1555), con el sello imperial", fit:"contain", la:"Cuius regio, eius religio", es:"A tal territorio, tal religión.",
  o:"Fórmula del jurista Joachim Stephani (hacia 1612) para resumir la Paz de Augsburgo (1555)",
  sen:"Cada príncipe decide la religión de su territorio. Así se puso fin a las guerras de religión del Imperio, a costa de la libertad de conciencia de los súbditos.",
  uso:"Para la Reforma protestante y el origen de la tolerancia.",
  amb:"politica", e:"ren", t:["hf-modernidad", "hf-contrato", "fil-t6"] },
{ id:"deussive", img:"media/galeria_museo/adagios/deussive.jpg", pie:"Portada de la Ética de Spinoza en sus obras póstumas (1677)", fit:"contain", la:"Deus sive Natura", es:"Dios, o sea, la Naturaleza.",
  o:"Spinoza, Ética IV, prefacio y proposición 4",
  sen:"Dios no está fuera del mundo: es la única sustancia, y la naturaleza es Dios mismo. Por eso le acusaron de ateo.",
  uso:"Para Spinoza y el debate metafísico moderno.",
  amb:"realidad", e:"mod", t:["hf-metafisica"] },
{ id:"examen", img:"media/galeria_museo/adagios/examen.jpg", pie:"Busto de Sócrates, copia romana de un original griego del siglo IV a. C. (Museos Vaticanos)", la:"Ho anexétastos bíos ou biotós", gr:"Ὁ δὲ ἀνεξέταστος βίος οὐ βιωτὸς ἀνθρώπῳ", tr:"ho de anexétastos bíos ou biotós anthrópoi", es:"Una vida sin examen no merece ser vivida.",
  o:"Platón, Apología de Sócrates 38a",
  sen:"Sócrates lo dice ante el tribunal que lo juzga: prefiere morir antes que dejar de examinarse a sí mismo y a los demás. Vivir como un ser humano es preguntarse por qué hacemos lo que hacemos.",
  uso:"Para explicar para qué sirve la filosofía o para presentar a Sócrates.",
  trampa:"No dice que la vida de quien no filosofa valga menos, sino que examinarse forma parte de vivir bien. Sócrates no pide escribir tratados: pide hacerse preguntas.",
  amb:"humano", e:"ant", t:["hf-sofistas", "hf-antropologia", "fil-t1"] },
{ id:"geometria", img:"media/galeria_museo/adagios/geometria.jpg", pie:"Mosaico de la Academia de Platón, de una villa de Pompeya (siglo I; Museo Arqueológico de Nápoles)", la:"Ageometretos medeis eisito", gr:"Ἀγεωμέτρητος μηδεὶς εἰσίτω", tr:"ageométretos medéis eisíto", es:"Que no entre nadie que no sepa geometría.",
  o:"Inscripción que la tradición sitúa a la entrada de la Academia de Platón; la transmiten comentaristas de Aristóteles del siglo VI, como Juan Filópono y Elías",
  sen:"Para Platón, las matemáticas educan la mente para pensar lo que no se ve con los ojos: son el paso previo para llegar a las Ideas.",
  uso:"Para Platón, la teoría de las Ideas y la línea dividida.",
  trampa:"No hay ninguna prueba de que la inscripción existiera en tiempos de Platón: aparece casi mil años después. Lo que sí es de Platón es el lugar de las matemáticas en la educación del filósofo (República VII).",
  amb:"saber", e:"ant", t:["hf-platon", "hf-ap"] },
{ id:"arche", img:"media/galeria_museo/adagios/arche.jpg", pie:"Busto de Bías de Priene con su nombre en griego, copia romana (Museos Vaticanos)", la:"Magistratus virum indicat", gr:"Ἀρχὴ ἄνδρα δείκνυσι", tr:"arkhé ándra deíknysi", es:"El cargo muestra quién es cada uno.", er:"I, x, 76",
  o:"Sentencia atribuida a Bías de Priene, uno de los Siete Sabios; la cita Aristóteles, Ética a Nicómaco V, 1, 1130a",
  sen:"Mientras no tiene poder, cualquiera parece justo. Es al mandar, cuando sus decisiones afectan a otros, cuando se ve de verdad cómo es una persona.",
  uso:"Para la justicia, la política o el mito del anillo de Giges.",
  amb:"politica", e:"ant", t:["hf-etica", "hf-politica", "fil-t6"] },
{ id:"primum", img:"media/galeria_museo/adagios/primum.jpg", pie:"Banquete de bodas campesino, de Pieter Bruegel el Viejo (hacia 1568; Kunsthistorisches Museum, Viena)", la:"Primum vivere, deinde philosophari", es:"Primero vivir, después filosofar.",
  o:"Fórmula tradicional, atribuida a veces a Hobbes sin confirmación; una idea parecida aparece en el poeta griego Focílides: «busca primero el sustento, y después la virtud»",
  sen:"Antes de pensar hay que comer: la filosofía necesita que estén cubiertas las necesidades básicas. Aristóteles ya decía que la filosofía nació cuando hubo tiempo libre.",
  uso:"Para el origen de la filosofía o para la relación entre las condiciones materiales y el pensamiento (Marx).",
  trampa:"No significa que filosofar sea un lujo inútil. A menudo se usa para decir lo contrario: que solo quien vive con dignidad puede pensar con libertad.",
  amb:"humano", e:"mod", t:["hf-mito", "hf-sospecha", "fil-t1"] },
{ id:"ancilla", img:"media/galeria_museo/adagios/ancilla.jpg", pie:"El triunfo de santo Tomás de Aquino, de Benozzo Gozzoli (hacia 1470; Museo del Louvre): Aristóteles y Platón a sus lados, Averroes a sus pies", la:"Philosophia ancilla theologiae", es:"La filosofía es la sierva de la teología.",
  o:"Fórmula escolástica; la imagen viene de Filón y Clemente de Alejandría y se atribuye a Pedro Damián (siglo XI), aunque la fórmula exacta se generalizó mucho después",
  sen:"La razón está al servicio de la fe: sirve para explicar y defender lo que se cree, no para juzgarlo.",
  uso:"Para el tema de fe y razón en la Edad Media.",
  trampa:"No todos los medievales pensaban así. Tomás de Aquino reconoce a la filosofía su propio campo, y Averroes defendía que la verdad de la razón no contradice la de la fe.",
  amb:"saber", e:"med", t:["hf-fe-razon", "hf-medieval"] },
{ id:"gratia", img:"media/galeria_museo/adagios/gratia.jpg", pie:"Triunfo de santo Tomás de Aquino sobre los herejes, de Filippino Lippi (1489-1491; capilla Carafa, Santa Maria sopra Minerva, Roma)", la:"Gratia non tollit naturam, sed perficit", es:"La gracia no destruye la naturaleza, sino que la perfecciona.",
  o:"Tomás de Aquino, Suma teológica I, q. 1, a. 8, ad 2",
  sen:"Lo que Dios da por la fe no anula lo que el ser humano alcanza por sí mismo con la razón, sino que lo completa. Fe y razón colaboran.",
  uso:"Para la síntesis de Tomás de Aquino entre Aristóteles y el cristianismo.",
  amb:"saber", e:"med", t:["hf-fe-razon", "hf-medieval"] },
{ id:"adaequatio", img:"media/galeria_museo/adagios/adaequatio.jpg", pie:"Santo Tomás de Aquino, de Carlo Crivelli (1476; National Gallery, Londres)", la:"Veritas est adaequatio rei et intellectus", es:"La verdad es la adecuación entre la cosa y el entendimiento.",
  o:"Tomás de Aquino, De veritate q. 1, a. 1, que la atribuye a Isaac Israelí; la idea viene de Aristóteles, Metafísica IV, 7",
  sen:"Un enunciado es verdadero cuando lo que pensamos coincide con lo que las cosas son. Es la teoría de la verdad como correspondencia.",
  uso:"Para las teorías de la verdad en teoría del conocimiento.",
  trampa:"No es la única definición posible: hay teorías de la verdad como coherencia o como consenso, y los pragmatistas la entienden como lo que funciona.",
  amb:"saber", e:"med", t:["fil-t3", "hf-medieval"] },
{ id:"recipitur", img:"media/galeria_museo/adagios/recipitur.jpg", pie:"La lechera, de Johannes Vermeer (hacia 1660; Rijksmuseum, Ámsterdam): la leche toma la forma de la vasija", la:"Quidquid recipitur ad modum recipientis recipitur", es:"Todo lo que se recibe, se recibe al modo de quien lo recibe.",
  o:"Axioma escolástico; Tomás de Aquino, Suma teológica I, q. 75, a. 5; su origen está en el neoplatonismo del Libro de las causas",
  sen:"Quien recibe algo lo transforma según su propia naturaleza, como el líquido toma la forma del recipiente. Con el conocimiento pasa lo mismo: cada uno entiende según su capacidad.",
  uso:"Para la teoría del conocimiento, de la escolástica a Kant, o para hablar de cómo se recibe una obra.",
  amb:"saber", e:"med", t:["fil-t3", "hf-kant", "hf-medieval"] },
{ id:"parendo", img:"media/galeria_museo/adagios/parendo.jpg", pie:"Francis Bacon, retrato atribuido a Paul van Somer (1617)", la:"Natura non nisi parendo vincitur", es:"A la naturaleza solo se la vence obedeciéndola.",
  o:"Francis Bacon, Novum Organum I, 3 (1620)",
  sen:"Para dominar la naturaleza hay que conocer sus leyes y respetarlas. Saber y poder van juntos.",
  uso:"Para Bacon, la revolución científica o la técnica.",
  trampa:"No es una llamada a respetar la naturaleza en sentido ecologista: Bacon quería conocerla para dominarla mejor.",
  amb:"saber", e:"ren", t:["hf-modernidad", "fil-t3"] },
{ id:"etsi", img:"media/galeria_museo/adagios/etsi.jpg", pie:"Hugo Grocio, de Michiel van Mierevelt (1631)", la:"Etsi Deus non daretur", es:"Aunque Dios no existiera.",
  o:"Hugo Grocio, Del derecho de la guerra y de la paz (1625), Prolegómenos, 11: «aunque concediéramos [...] que Dios no existe»; la fórmula breve es posterior",
  sen:"Las normas básicas de la justicia valdrían aunque Dios no existiera, porque se fundan en la naturaleza humana y en la razón. Es el punto de partida del derecho natural moderno.",
  uso:"Para el derecho natural, el contrato social o la laicidad.",
  trampa:"Grocio era creyente: no niega a Dios, sino que muestra que el derecho no depende de la fe de cada uno. Añade que suponer que Dios no existe sería un gravísimo pecado.",
  amb:"politica", e:"mod", t:["hf-contrato", "fil-t6", "fil-t5"] },
{ id:"aeternitatis", img:"media/galeria_museo/adagios/aeternitatis.jpg", pie:"Retrato de Spinoza, anónimo holandés (hacia 1665-1666)", la:"Sub specie aeternitatis", es:"Desde la perspectiva de la eternidad.",
  o:"Spinoza, Ética II, proposición 44, corolario 2 («sub quadam aeternitatis specie»), y Ética V",
  sen:"Es propio de la razón ver las cosas como necesarias, no como accidentes del momento. Mirarlas así libera de las pasiones y da una alegría serena.",
  uso:"Para Spinoza o para hablar de tomar distancia de lo inmediato.",
  amb:"realidad", e:"mod", t:["hf-metafisica"] },
{ id:"saltus", img:"media/galeria_museo/adagios/saltus.jpg", pie:"Portada de la Philosophia botanica de Linneo (Estocolmo, 1751), donde aparece la fórmula latina", fit:"contain", la:"Natura non facit saltus", es:"La naturaleza no da saltos.",
  o:"Leibniz, Nuevos ensayos sobre el entendimiento humano, prefacio: «la naturaleza nunca da saltos»; la fórmula latina, en Linneo, Philosophia botanica (1751)",
  sen:"En la naturaleza todo cambia de forma gradual, sin rupturas: entre dos estados siempre hay intermedios. Es la ley de continuidad de Leibniz.",
  uso:"Para Leibniz, la clasificación de los seres vivos o la evolución de Darwin, que la repite.",
  trampa:"La física del siglo XX la pone en duda: en la mecánica cuántica la energía cambia a saltos.",
  amb:"realidad", e:"mod", t:["hf-metafisica", "fil-metafisica"] },
{ id:"determinatio", img:"media/galeria_museo/adagios/determinatio.jpg", pie:"Hegel, de Jakob Schlesinger (1831)", la:"Omnis determinatio est negatio", es:"Toda determinación es una negación.",
  o:"Spinoza, carta 50 a Jarig Jelles (1674): «determinatio negatio est»; Hegel la convirtió en fórmula, con «omnis»",
  sen:"Decir lo que algo es supone decir lo que no es: definir es poner límites. Para Hegel, la negación es el motor del pensamiento y de la realidad.",
  uso:"Para Spinoza, Hegel y la dialéctica, también la de Marx.",
  amb:"realidad", e:"mod", t:["hf-metafisica", "hf-sospecha", "fil-metafisica"] },
{ id:"carro", img:"media/galeria_museo/adagios/carro.jpg", pie:"«El mundo al revés», aleluya flamenca (Turnhout, hacia 1880): un buey siega la hierba y un gallo empolla los huevos", fit:"contain", la:"Currus bovem trahit", es:"Poner el carro delante del caballo.", er:"I, vii, 28",
  o:"«El carro tira del buey», proverbio sobre lo que se hace al revés",
  sen:"Hacer las cosas en el orden equivocado, empezar por el final. En lógica es invertir causa y efecto, o dar por probado lo que se quiere probar.",
  uso:"Para la argumentación y las falacias: confundir causa y efecto, o la petición de principio.",
  trampa:"En castellano se dice también «delante de los bueyes», que es la imagen de Erasmo: un carro que tira de los animales en vez de ser arrastrado por ellos.",
  amb:"saber", e:"ren", t:["fil-t4", "hf-metodos"] },
{ id:"necesidad", img:"media/galeria_museo/adagios/necesidad.jpg", pie:"Portada de Nova reperta («Nuevos inventos»), grabado según Jan van der Straet (hacia 1590)", la:"Necessitas magistra", es:"La necesidad es la madre de la invención.", er:"IV, vi, 55",
  o:"La idea está en Platón, República II, 369c, donde Sócrates dice de la ciudad que «la creará nuestra necesidad»; el poeta romano Persio llama al estómago «maestro de las artes» (Sátiras, prólogo)",
  sen:"Las técnicas, los oficios y hasta las ciudades nacen para satisfacer necesidades: cuando algo nos falta, nos ingeniamos para conseguirlo.",
  uso:"Para el origen de la técnica, de la sociedad o de la ciudad en Platón.",
  trampa:"La frase con «madre» no es de Platón: la hizo célebre una traducción inglesa del siglo XIX, la de Benjamin Jowett.",
  amb:"humano", e:"ant", t:["hf-politica", "hf-platon", "fil-t6"] },
{ id:"hecho", img:"media/galeria_museo/adagios/hecho.jpg", pie:"Vanidad, de Philippe de Champaigne (1646; Museo de Tessé, Le Mans): un tulipán, una calavera y un reloj de arena", la:"Quod factum est, infectum fieri non potest", gr:"μόνου γὰρ αὐτοῦ καὶ θεὸς στερίσκεται, ἀγένητα ποιεῖν ἅσσ᾽ ἂν ᾖ πεπραγμένα", tr:"mónou gar autoú kai theós sterísketai, agéneta poiéin háss' an ei pepragména", es:"A lo hecho, pecho.", er:"II, iii, 72",
  o:"El refrán castellano tiene un antecedente en el poeta Agatón, citado por Aristóteles, Ética a Nicómaco VI, 2, 1139b: «de esto solo está privado incluso Dios: de hacer que no haya ocurrido lo que ya se hizo»; en latín, Plauto, Aulularia 741",
  sen:"Lo hecho no se puede deshacer, así que hay que asumir sus consecuencias. Aristóteles cita el verso para explicar que solo deliberamos sobre el futuro, no sobre el pasado.",
  uso:"Para la responsabilidad moral, la deliberación en Aristóteles o el debate sobre si Dios puede cambiar el pasado.",
  trampa:"El refrán pide asumir las consecuencias; el verso griego dice algo más fuerte: ni siquiera la omnipotencia puede cambiar el pasado.",
  amb:"etica", e:"ant", t:["hf-etica", "fil-t5"] },
{ id:"habito", img:"media/galeria_museo/adagios/habito.jpg", pie:"San Francisco en meditación, de Francisco de Zurbarán (1639; National Gallery, Londres)", la:"Cucullus non facit monachum", es:"El hábito no hace al monje.",
  o:"Proverbio latino medieval de origen incierto; lo cita Shakespeare en Noche de Reyes (I, 5) y en Medida por medida (V, 1)",
  sen:"La apariencia no cambia lo que uno es: vestir como un monje no hace a nadie santo. Hay que juzgar por los actos, no por la imagen.",
  uso:"Para la distinción entre apariencia y realidad o para la crítica de la hipocresía.",
  trampa:"No quiere decir que la apariencia no importe nada: advierte de que no basta.",
  amb:"humano", e:"med", t:["hf-platon", "fil-t3"] },
{ id:"oro", img:"media/galeria_museo/adagios/oro.jpg", pie:"El alquimista, de David Teniers el Joven (hacia 1640-1650; Mauritshuis, La Haya)", la:"Non teneas aurum totum quod splendet ut aurum", es:"No es oro todo lo que reluce.",
  o:"Alain de Lille, Libro de las parábolas (siglo XII): «no tengas por oro todo lo que brilla como el oro»",
  sen:"Lo que parece valioso no siempre lo es. Las apariencias engañan, y hay que examinar antes de fiarse.",
  uso:"Para la diferencia entre apariencia y realidad, la caverna de Platón o el pensamiento crítico ante la información.",
  trampa:"No dice que nada de lo que brilla sea oro, sino que no lo es todo. La conclusión prudente es examinar, no despreciar.",
  amb:"saber", e:"med", t:["hf-platon", "fil-t3"] },
{ id:"taurum", img:"media/galeria_museo/adagios/taurum.jpg", pie:"El Moscóforo, estatua de un hombre que carga un ternero (hacia 570 a. C.), recién desenterrado en la Acrópolis de Atenas (fotografía de hacia 1865)", la:"Taurum tollet, qui vitulum sustulerit", es:"Quien ha cargado con el ternero, cargará con el toro.", er:"I, ii, 51",
  o:"Proverbio antiguo que recoge Erasmo; Montaigne cuenta en los Ensayos I, 23 («De la costumbre») el caso de una campesina que, a fuerza de llevar en brazos a un ternero, seguía cargándolo cuando ya era un buey",
  sen:"La costumbre hace posible lo que parecía imposible: lo que se hace poco a poco, cada día, acaba pareciendo natural. Por eso, para Montaigne, la costumbre es tan poderosa, para bien y para mal.",
  uso:"Para la fuerza de la costumbre y de los hábitos (Aristóteles, Hume) o para Montaigne.",
  trampa:"Montaigne no lo cuenta como un elogio del esfuerzo, sino como una advertencia: la costumbre nos acostumbra también a lo absurdo y nos impide verlo.",
  amb:"humano", e:"ant", t:["hf-montaigne-ensayos", "hf-racionalismo", "fil-t2"] },
{ id:"mores", img:"media/galeria_museo/adagios/mores.jpg", pie:"Némesis o La gran fortuna, grabado de Alberto Durero (hacia 1501-1502)", fit:"contain", la:"Sui cuique mores fingunt fortunam", es:"A cada uno, su carácter le forja la fortuna.", er:"II, iv, 30",
  o:"Verso que cita Cornelio Nepote, Vida de Ático 11; Erasmo lo comenta largamente, y Montaigne cierra con él el ensayo I, 42 («De la desigualdad que hay entre nosotros»)",
  sen:"La suerte de cada uno depende más de su carácter que del azar. Montaigne lo usa al final de un ensayo sobre la desigualdad: lo que distingue de verdad a unas personas de otras no es su riqueza ni su cargo, sino lo que son.",
  uso:"Para el carácter y la fortuna en la ética (los estoicos, Maquiavelo) o para Montaigne.",
  trampa:"No significa que cada uno tenga lo que se merece: Montaigne critica precisamente que juzguemos a las personas por su fortuna exterior.",
  amb:"etica", e:"ant", t:["hf-montaigne-ensayos", "hf-etica", "fil-t5"] },
{ id:"sellis", img:"media/galeria_museo/adagios/sellis.jpg", pie:"Los proverbios flamencos, de Pieter Bruegel el Viejo (1559; Gemäldegalerie, Berlín): entre más de cien refranes pintados está el de quien acaba en la ceniza entre dos taburetes", la:"Duabus sedere sellis", es:"Estar sentado entre dos sillas.", er:"I, vii, 2",
  o:"Proverbio antiguo que recoge Erasmo; Montaigne lo usa en los Ensayos I, 54 («De las vanas sutilezas») para los medio sabios, que se han quedado «entre dos sillas»",
  sen:"Quien no se decide entre dos posturas acaba sin ninguna. Montaigne lo aplica al saber: los campesinos sencillos y los verdaderos filósofos son gente de bien; los que hacen daño son los que han dejado la ignorancia natural sin llegar a la sabiduría.",
  uso:"Para la indecisión, el término medio mal entendido o la crítica de Montaigne a los pedantes.",
  amb:"saber", e:"ant", t:["hf-montaigne-ensayos", "fil-t3"] },
{ id:"lucernam", img:"media/galeria_museo/adagios/lucernam.jpg", pie:"Astrónomo a la luz de la vela, de Gerrit Dou (hacia 1656-1659; Getty Museum)", la:"Olet lucernam", es:"Huele a lámpara.", er:"I, vii, 71",
  o:"Plutarco, Vida de Demóstenes 8: un rival decía que los discursos de Demóstenes olían a lámpara; Erasmo lo recoge, y Montaigne lo usa en los Ensayos I, 10 («Del hablar rápido o lento»)",
  sen:"Una obra que «huele a lámpara» deja ver demasiado el esfuerzo de las noches de trabajo: se nota rígida, poco natural. Montaigne prefería la palabra que parece espontánea.",
  uso:"Para el estilo, la escritura de ensayos o la improvisación frente a la preparación.",
  trampa:"Montaigne no desprecia el trabajo: dice que hay ingenios que necesitan prepararse y otros que brillan improvisando, y que cada uno debe conocer el suyo.",
  amb:"humano", e:"ant", t:["hf-montaigne-ensayos"] },
{ id:"crastinum", img:"media/galeria_museo/adagios/crastinum.jpg", pie:"Plutarco, en un grabado de 1565. Montaigne leía sus Vidas en la traducción francesa de Jacques Amyot", la:"In crastinum seria", es:"Los asuntos serios, para mañana.", er:"IV, vii, 60",
  o:"Plutarco, Vida de Pelópidas 10: lo dijo Arquías, tirano de Tebas, al dejar sin abrir la carta que le avisaba de la conjura contra él; Erasmo lo recoge, y Montaigne titula con él el ensayo II, 4 («A mañana los asuntos»)",
  sen:"Dejar para mañana lo urgente puede costar caro: Arquías murió esa misma noche. Montaigne matiza que un sabio puede aplazar una noticia por cortesía o por un asunto más importante, pero no por su propio placer.",
  uso:"Para la prudencia, la tendencia a aplazar lo importante o el ensayo de Montaigne.",
  amb:"etica", e:"ant", t:["hf-montaigne-ensayos", "hf-etica"] },
{ id:"stultitia", img:"media/galeria_museo/adagios/stultitia.jpg", pie:"Página de los Ensayos de Montaigne en la edición de 1595", fit:"contain", la:"In nihil sapiendo iucundissima vita", gr:"Ἐν τῷ φρονεῖν γὰρ μηδὲν ἥδιστος βίος", tr:"en to phronéin gar medén hédistos bíos", es:"La vida más dulce es no saber nada.", er:"II, x, 81",
  o:"Sófocles, Áyax 554. Erasmo reúne bajo este adagio ejemplos y citas que Montaigne copia casi en bloque en la «Apología de Raimundo Sabunde» (Ensayos II, 12). Montaigne conocía tan bien los Adagios que escribió que, si hubiera visto a Erasmo, habría tomado por adagio todo lo que dijera a su criado (III, 2)",
  sen:"El que no sabe ni sospecha no sufre: a veces la ignorancia parece más feliz que la sabiduría. Montaigne cuenta el caso de un hombre que se creía dueño de todos los barcos que llegaban al Pireo y lamentó que lo curaran.",
  uso:"Para el escepticismo de Montaigne, la «Apología» o el debate sobre si saber hace feliz (el Eclesiastés: «en mucha sabiduría hay mucho sufrimiento»).",
  trampa:"Montaigne no hace un elogio de la ignorancia sin más: la usa para bajar los humos a la razón orgullosa. Y la frase la dice Áyax en una tragedia, no un filósofo.",
  amb:"saber", e:"ant", t:["hf-montaigne-ensayos", "hf-helenismo", "fil-t1"] }
];
