"use strict";
/* ===== «Adagios: el lenguaje común de la filosofía» (09-10, Bachillerato) — datos =====
   Repertorio de lemas y adagios clásicos al estilo de los cuadernos de lugares comunes del Renacimiento.
   Campos: id; la = lema en latín (o la forma con que circula); gr = original griego, si lo hay, y tr = su transliteración (convención del glosario); es = traducción;
   o = de dónde viene (obra y pasaje; «fórmula tradicional» cuando no es literal); er = número en los Adagia de
   Erasmo (solo cuando consta); sen = qué quiere decir; uso = cuándo usarlo; trampa = error frecuente;
   amb = ámbito (saber | realidad | etica | politica | humano); e = época de origen (ant | med | ren | mod),
   para el color; t = temas de Teoría (ids de theory.js; la vista solo enlaza los que existen en cada web);
   img y pie = imagen de dominio público (créditos en recursos/imagenes_museos/adagios/) y su pie; fit:"contain" = no recortar (portadas, grabados, planos).
   Vista: adagiosview.js. Solo Bachillerato (build_eso.js lo deja fuera). */
const ADAGIOS = [
{ id:"amicorum", img:"media/galeria_museo/adagios/amicorum.jpg", pie:"Pitágoras, en La escuela de Atenas de Rafael (1509-1511)", la:"Amicorum communia omnia", gr:"Κοινὰ τὰ τῶν φίλων", tr:"koiná ta ton phílon", es:"Entre amigos, todo es común.",
  o:"Proverbio pitagórico que recogen Platón (Fedro 279c; Leyes V, 739c) y Aristóteles (Ética a Nicómaco VIII, 9)", er:"I, i, 1",
  sen:"La amistad verdadera no lleva cuentas: lo que es de uno es del otro. Erasmo lo puso el primero de toda su colección y lo leyó también como el germen de una sociedad que comparte sus bienes.",
  uso:"Para hablar de la amistad en Aristóteles o de la propiedad común de los guardianes en la República de Platón.",
  amb:"etica", e:"ant", t:["hf-etica", "hf-politica", "fil-t5"] },
{ id:"nosce", img:"media/galeria_museo/adagios/nosce.jpg", pie:"La sacerdotisa de Delfos, de John Collier (1891)", la:"Nosce te ipsum", gr:"Γνῶθι σεαυτόν", tr:"gnóthi seautón", es:"Conócete a ti mismo.",
  o:"Inscripción del templo de Apolo en Delfos; Platón la comenta en Protágoras 343b y Cármides 164d", er:"I, vi, 95",
  sen:"En Delfos era una advertencia: recuerda que eres mortal y no un dios. Sócrates la convirtió en un programa: examinar la propia vida y saber lo que uno no sabe.",
  uso:"Para presentar a Sócrates o para empezar cualquier tema sobre el ser humano.",
  amb:"humano", e:"ant", t:["hf-sofistas", "hf-antropologia", "fil-t2"] },
{ id:"nequid", img:"media/galeria_museo/adagios/nequid.jpg", pie:"Paisaje con la caída de Ícaro, atribuido a Pieter Bruegel el Viejo (hacia 1560): Ícaro voló demasiado alto", la:"Ne quid nimis", gr:"Μηδὲν ἄγαν", tr:"medén ágan", es:"Nada en exceso.",
  o:"Otra de las inscripciones de Delfos; en latín, Terencio, La andriana 61", er:"I, vi, 96",
  sen:"La sabiduría griega desconfía de todo exceso. Es la raíz popular de la virtud como término medio entre dos vicios.",
  uso:"Para explicar el término medio de Aristóteles.",
  trampa:"Aristóteles no defiende la mediocridad: el término medio es lo mejor, un extremo de excelencia, y no se calcula con una regla, sino con la prudencia.",
  amb:"etica", e:"ant", t:["hf-etica", "fil-t5"] },
{ id:"festina", img:"media/galeria_museo/adagios/festina.jpg", pie:"El ancla y el delfín, marca del impresor Aldo Manucio (Moralia de Plutarco, Venecia, 1509)", fit:"contain", la:"Festina lente", gr:"Σπεῦδε βραδέως", tr:"speúde bradéos", es:"Apresúrate despacio.",
  o:"Suetonio, Vida de Augusto 25: el emperador lo repetía a menudo", er:"II, i, 1",
  sen:"Une dos virtudes que parecen opuestas: decisión y prudencia. El impresor Aldo Manucio lo hizo su emblema con un delfín (rapidez) enroscado en un ancla (firmeza), y Erasmo le dedicó uno de sus comentarios más largos.",
  uso:"Para hablar de la prudencia o del método: avanzar, pero con orden.",
  amb:"etica", e:"ant", t:["hf-modernidad", "fil-t5"] },
{ id:"sileni", img:"media/galeria_museo/adagios/sileni.jpg", pie:"Alcibíades recibe las enseñanzas de Sócrates, de François-André Vincent (1776)", la:"Sileni Alcibiadis", es:"Los silenos de Alcibíades.",
  o:"Platón, Banquete 215a-b: Alcibíades compara a Sócrates con las figuras de sileno que se abrían y tenían dentro imágenes de dioses", er:"III, iii, 1",
  sen:"Lo valioso suele tener un exterior feo o humilde, y lo que brilla por fuera puede estar vacío. Sócrates, feo y pobre, guardaba dentro la sabiduría.",
  uso:"Para distinguir entre apariencia y realidad, o para describir a Sócrates.",
  amb:"saber", e:"ant", t:["hf-sofistas", "hf-platon", "fil-t1"] },
{ id:"spartam", img:"media/galeria_museo/adagios/spartam.jpg", pie:"Jóvenes espartanos ejercitándose, de Edgar Degas (hacia 1860)", la:"Spartam nactus es, hanc orna", gr:"Σπάρταν ἔλαχες, κείναν κόσμει", tr:"Spártan élakhes, keínan kósmei", es:"Te ha tocado Esparta: adórnala.",
  o:"Verso de Eurípides (tragedia perdida Télefo); lo cita Cicerón en sus cartas a Ático (IV, 6)", er:"II, v, 1",
  sen:"Haz bien el papel que te ha tocado en vez de envidiar el de otro. Erasmo lo aplicó a los príncipes: que gobiernen bien su reino antes de soñar con conquistar otros.",
  uso:"Para la ética estoica (aceptar el papel que te toca) o para criticar las guerras de conquista.",
  amb:"etica", e:"ant", t:["hf-helenismo", "fil-helenismo"] },
{ id:"dulce", img:"media/galeria_museo/adagios/dulce.jpg", pie:"El triunfo de la muerte, de Pieter Bruegel el Viejo (hacia 1562)", la:"Dulce bellum inexpertis", es:"La guerra es dulce para quien no la ha probado.",
  o:"Píndaro (fragmento 110), en latín por Vegecio", er:"IV, i, 1",
  sen:"Solo ensalza la guerra quien no la conoce. Erasmo lo convirtió en un largo alegato contra la guerra entre cristianos, que se imprimió muchas veces como libro aparte.",
  uso:"Para hablar del pacifismo humanista o de la paz perpetua de Kant.",
  amb:"politica", e:"ant", t:["hf-modernidad", "hf-kant", "fil-t6"] },
{ id:"scarabeus", img:"media/galeria_museo/adagios/scarabeus.jpg", pie:"El águila y el escarabajo, grabado de Wenceslaus Hollar (siglo XVII)", fit:"contain", la:"Scarabeus aquilam quaerit", es:"El escarabajo persigue al águila.",
  o:"Fábula de Esopo: el escarabajo se venga del águila rompiéndole los huevos", er:"III, vii, 1",
  sen:"Ni el más débil es despreciable: también puede vengarse del poderoso. Erasmo lo usó para criticar a los reyes que se comportan como aves de rapiña.",
  uso:"Para hablar del poder y de sus límites.",
  amb:"politica", e:"ant", t:["hf-contrato", "fil-t6"] },
{ id:"autregem", img:"media/galeria_museo/adagios/autregem.jpg", pie:"El bufón Calabacillas, de Diego Velázquez (hacia 1636-1638)", la:"Aut regem aut fatuum nasci oportere", es:"Hay que nacer rey o tonto.",
  o:"Séneca, Apocolocyntosis 1 (sátira sobre la muerte del emperador Claudio)", er:"I, iii, 1",
  sen:"Solo a los reyes y a los bufones se les perdona todo. Erasmo aprovecha el adagio para escribir un pequeño tratado sobre cómo debe ser un buen príncipe.",
  uso:"Para hablar de la educación del gobernante (Platón, Erasmo, Maquiavelo).",
  amb:"politica", e:"ant", t:["hf-politica", "hf-contrato", "fil-t6"] },
{ id:"herculei", img:"media/galeria_museo/adagios/herculei.jpg", pie:"Hércules lucha con la hidra de Lerna, de Francisco de Zurbarán (1634)", la:"Herculei labores", es:"Trabajos de Hércules.",
  o:"Los doce trabajos del mito de Heracles", er:"III, i, 1",
  sen:"Una tarea enorme e ingrata. Erasmo lo usó para hablar de su propio trabajo: reunir y comentar miles de adagios le parecía un trabajo de Hércules.",
  uso:"Para hablar de proyectos enormes como la Enciclopedia o los Adagia.",
  amb:"humano", e:"ant", t:["hf-modernidad", "hf-ilustracion"] },
{ id:"lupus", img:"media/galeria_museo/adagios/lupus.jpg", pie:"Portada del Leviatán de Hobbes, grabada por Abraham Bosse (1651)", fit:"contain", la:"Homo homini lupus", es:"El hombre es un lobo para el hombre.",
  o:"Plauto, Asinaria 495, con las palabras en otro orden; Hobbes, De cive, carta dedicatoria (1642)", er:"I, i, 70",
  sen:"Entre desconocidos, sin ley que nos proteja, el otro es una amenaza. Hobbes la usa para describir el estado de naturaleza.",
  uso:"Para el estado de naturaleza y el contrato social.",
  trampa:"La frase no es de Hobbes, sino de Plauto, y en la misma carta Hobbes pone la contraria: «el hombre es un dios para el hombre» (entre ciudadanos que viven bajo leyes). En Plauto, además, la frase dice que el hombre es un lobo para quien no conoce.",
  amb:"politica", e:"ant", t:["hf-contrato", "fil-t6"] },
{ id:"zoon", img:"media/galeria_museo/adagios/zoon.jpg", pie:"Pericles pronuncia la oración fúnebre, estampa según Philipp Foltz (hacia 1875-1880)", la:"Animal politicum", gr:"Ζῷον πολιτικόν", tr:"zóon politikón", es:"El ser humano es un animal político.",
  o:"Aristóteles, Política I, 2, 1253a",
  sen:"El ser humano solo se realiza plenamente en la ciudad (polis), porque tiene palabra (logos) para discutir qué es justo. Quien puede vivir solo, dice Aristóteles, es una bestia o un dios.",
  uso:"Para la política clásica o para comparar con el contrato social.",
  trampa:"«Político» no quiere decir que nos guste la política de partidos, sino que somos seres de la polis: necesitamos la comunidad para vivir bien.",
  amb:"politica", e:"ant", t:["hf-politica", "hf-antropologia", "fil-t6", "fil-t2"] },
{ id:"pantarhei", img:"media/galeria_museo/adagios/pantarhei.jpg", pie:"Heráclito, de Johannes Moreelse (hacia 1630)", la:"Panta rhei", gr:"Πάντα ῥεῖ", tr:"pánta rhei", es:"Todo fluye.",
  o:"Fórmula tradicional atribuida a Heráclito; cf. Platón, Crátilo 402a: «todo se mueve y nada permanece»",
  sen:"La realidad es cambio continuo: no te puedes bañar dos veces en el mismo río.",
  uso:"Para los presocráticos y el problema del cambio.",
  trampa:"La fórmula exacta no aparece en ningún fragmento de Heráclito. Además, para él el cambio no es caos: sigue una medida, el logos, que mantiene unidos los contrarios.",
  amb:"realidad", e:"ant", t:["hf-preso", "fil-presocraticos"] },
{ id:"exnihilo", img:"media/galeria_museo/adagios/exnihilo.jpg", pie:"Separación de la luz y las tinieblas, de Miguel Ángel (Capilla Sixtina, 1511)", la:"Ex nihilo nihil fit", es:"De la nada, nada sale.",
  o:"Principio que recorre la filosofía griega desde Parménides; en latín, Lucrecio, De rerum natura I, 150-156",
  sen:"Todo lo que llega a ser procede de algo. Los griegos lo daban por evidente; la idea cristiana de creación «de la nada» (ex nihilo) chocó con él.",
  uso:"Para los presocráticos o para el debate entre fe y razón sobre la creación del mundo.",
  amb:"realidad", e:"ant", t:["hf-preso", "hf-fe-razon", "fil-presocraticos"] },
{ id:"mensura", img:"media/galeria_museo/adagios/mensura.jpg", pie:"Demócrito y Protágoras, de Salvator Rosa (hacia 1663-1664)", la:"Homo mensura", gr:"Πάντων χρημάτων μέτρον ἄνθρωπος", tr:"pánton khremáton métron ánthropos", es:"El hombre es la medida de todas las cosas.",
  o:"Protágoras, citado por Platón, Teeteto 152a",
  sen:"Las cosas son para cada uno tal como le aparecen: no hay una verdad que esté por encima de todos los puntos de vista.",
  uso:"Para los sofistas y el relativismo.",
  trampa:"No es un elogio del ser humano al estilo del Renacimiento, sino una tesis relativista: lo que a ti te parece verdad, es verdad para ti.",
  amb:"saber", e:"ant", t:["hf-sofistas", "fil-t3"] },
{ id:"solose", img:"media/galeria_museo/adagios/solose.jpg", pie:"La muerte de Sócrates, de Jacques-Louis David (1787)", la:"Scio me nihil scire", es:"Solo sé que no sé nada.",
  o:"Fórmula tradicional; cf. Platón, Apología 21d: «no creo saber lo que no sé»",
  sen:"El primer paso del saber es reconocer la propia ignorancia. El sabio no es el que lo sabe todo, sino el que sabe qué no sabe.",
  uso:"Para presentar la ironía socrática.",
  trampa:"Sócrates no dice que no sepa nada, que sería contradictorio, sino que no cree saber lo que no sabe. Es más sabio que los demás porque es consciente de sus límites.",
  amb:"saber", e:"ant", t:["hf-sofistas", "fil-t1"] },
{ id:"amicusplato", img:"media/galeria_museo/adagios/amicusplato.jpg", pie:"Platón y Aristóteles, en La escuela de Atenas de Rafael (1509-1511)", la:"Amicus Plato, sed magis amica veritas", es:"Platón es mi amigo, pero la verdad lo es más.",
  o:"Fórmula tradicional medieval; cf. Aristóteles, Ética a Nicómaco I, 6, 1096a",
  sen:"Antes que fiel a un maestro, hay que serlo a la verdad. Aristóteles lo dice al empezar su crítica de la Idea de Bien de Platón: es piadoso honrar la verdad antes que a los amigos.",
  uso:"Para la crítica de Aristóteles a Platón o para defender la libertad de pensar.",
  amb:"saber", e:"ant", t:["hf-platon", "hf-metodos", "fil-t1"] },
{ id:"tabula", img:"media/galeria_museo/adagios/tabula.jpg", pie:"Tablilla de cera con ejercicios escolares en griego (Egipto, siglo II; British Library)", fit:"contain", la:"Tabula rasa", es:"Tablilla en blanco.",
  o:"Aristóteles, Acerca del alma III, 4, 430a (la tablilla en que aún no hay nada escrito); Locke habla de un papel en blanco (Ensayo II, 1, 2)",
  sen:"La mente, al nacer, no trae ideas: todo lo escribe en ella la experiencia.",
  uso:"Para el empirismo y el debate sobre las ideas innatas.",
  amb:"saber", e:"ant", t:["hf-racionalismo", "fil-t3"] },
{ id:"nihilest", img:"media/galeria_museo/adagios/nihilest.jpg", pie:"La vista, de Jan Brueghel el Viejo y Rubens (1617; Museo del Prado)", la:"Nihil est in intellectu quod non prius fuerit in sensu", es:"No hay nada en el entendimiento que no haya estado antes en los sentidos.",
  o:"Axioma escolástico; Tomás de Aquino, De veritate q. 2, a. 3. Leibniz le añadió: «nisi ipse intellectus» («excepto el propio entendimiento»)",
  sen:"Todo conocimiento empieza por los sentidos. El empirismo lo hace suyo; Leibniz le pone una excepción decisiva: las estructuras de la propia mente.",
  uso:"Para el debate entre racionalismo y empirismo.",
  amb:"saber", e:"med", t:["hf-racionalismo", "hf-fe-razon", "fil-t3"] },
{ id:"credo", img:"media/galeria_museo/adagios/credo.jpg", pie:"San Agustín en su estudio, de Sandro Botticelli (hacia 1490-1494)", la:"Credo ut intelligam", es:"Creo para entender.",
  o:"Anselmo de Canterbury, Proslogion 1; antes, Agustín de Hipona: «crede ut intelligas» (Sermón 43)",
  sen:"La fe no sustituye a la razón: le abre el camino. Quien cree busca entender lo que cree.",
  uso:"Para las relaciones entre fe y razón en la Edad Media.",
  amb:"saber", e:"med", t:["hf-fe-razon", "hf-medieval"] },
{ id:"ockham", img:"media/galeria_museo/adagios/ockham.jpg", pie:"Ockham, dibujado al margen de un manuscrito de su Summa logicae (1341)", fit:"contain", la:"Entia non sunt multiplicanda praeter necessitatem", es:"No hay que multiplicar los entes sin necesidad.",
  o:"La «navaja de Ockham». Ockham escribe «pluralitas non est ponenda sine necessitate»; la fórmula famosa es de John Punch (1639)",
  sen:"Entre dos explicaciones, quédate con la que necesita menos supuestos. Ockham la usó para eliminar los universales como cosas reales.",
  uso:"Para el problema de los universales o para cualquier discusión sobre qué explicación es mejor.",
  trampa:"No dice que la explicación más simple sea siempre la verdadera, sino que no hay que añadir supuestos que no hacen falta.",
  amb:"saber", e:"med", t:["hf-medieval", "fil-t3", "fil-t4"] },
{ id:"scientia", img:"media/galeria_museo/adagios/scientia.jpg", pie:"Portada de la Instauratio magna de Francis Bacon (1620): una nave cruza las columnas de Hércules", fit:"contain", la:"Ipsa scientia potestas est", es:"El saber mismo es poder.",
  o:"Francis Bacon, Meditationes sacrae (1597); la idea vuelve en el Novum organum I, 3",
  sen:"Conocer las causas de la naturaleza permite dominarla. La ciencia moderna ya no busca solo contemplar, sino transformar el mundo.",
  uso:"Para la revolución científica o para la crítica de la razón instrumental.",
  amb:"saber", e:"ren", t:["hf-modernidad", "hf-capitalismo", "fil-t3"] },
{ id:"sapere", img:"media/galeria_museo/adagios/sapere.jpg", pie:"Comienzo de «¿Qué es la Ilustración?» de Kant en la Berlinische Monatsschrift (1784)", fit:"contain", la:"Sapere aude", es:"Atrévete a saber.",
  o:"Horacio, Epístolas I, 2, 40; Kant lo hace lema de la Ilustración en ¿Qué es la Ilustración? (1784)",
  sen:"Ten el valor de servirte de tu propio entendimiento, sin la guía de otro.",
  uso:"Para la Ilustración y Kant.",
  trampa:"No es de Kant: es un verso de Horacio, que hablaba de empezar a vivir bien sin aplazarlo. Kant lo reinterpreta como lema de la Ilustración.",
  amb:"saber", e:"ant", t:["hf-ilustracion", "hf-kant", "fil-t1"] },
{ id:"errare", img:"media/galeria_museo/adagios/errare.jpg", pie:"La parábola de los ciegos, de Pieter Bruegel el Viejo (1568)", la:"Errare humanum est", es:"Equivocarse es humano.",
  o:"Fórmula tradicional; cf. Cicerón, Filípicas XII, 5: «es propio de cualquiera equivocarse, y solo del necio perseverar en el error»",
  sen:"El error forma parte del conocimiento humano. Lo grave no es equivocarse, sino no corregirse.",
  uso:"Para el falibilismo o para el método científico.",
  amb:"saber", e:"ant", t:["fil-t3", "hf-metodos"] },
{ id:"carpe", img:"media/galeria_museo/adagios/carpe.jpg", pie:"Coged las rosas mientras podáis, de John William Waterhouse (1908)", la:"Carpe diem", es:"Aprovecha el día.",
  o:"Horacio, Odas I, 11, 8",
  sen:"No confíes en el mañana: vive bien el presente.",
  uso:"Para el epicureísmo.",
  trampa:"No significa «haz lo que te apetezca». Horacio es epicúreo: aprovechar el día es disfrutar con moderación de lo que hay, sin angustiarse por el futuro.",
  amb:"etica", e:"ant", t:["hf-helenismo", "fil-helenismo"] },
{ id:"latuit", img:"media/galeria_museo/adagios/latuit.jpg", pie:"Busto de Epicuro, copia romana (British Museum)", la:"Bene qui latuit, bene vixit", gr:"Λάθε βιώσας", tr:"láthe biósas", es:"Vivió bien quien vivió oculto.",
  o:"Ovidio, Tristes III, 4, 25; en griego, el lema de Epicuro «vive oculto»",
  sen:"La felicidad está lejos de la fama y la política, en una vida tranquila con los amigos.",
  uso:"Para el epicureísmo y el Jardín.",
  amb:"etica", e:"ant", t:["hf-helenismo", "fil-helenismo"] },
{ id:"sustine", img:"media/galeria_museo/adagios/sustine.jpg", pie:"Epicteto, grabado de Henri Bonnart (hacia 1700)", fit:"contain", la:"Sustine et abstine", gr:"Ἀνέχου καὶ ἀπέχου", tr:"anékhou kai apékhou", es:"Soporta y abstente.",
  o:"Epicteto, según Aulo Gelio, Noches áticas XVII, 19",
  sen:"Soporta lo que no depende de ti y abstente de lo que te esclaviza. Es el resumen estoico de la vida buena.",
  uso:"Para el estoicismo.",
  amb:"etica", e:"ant", t:["hf-helenismo", "fil-helenismo"] },
{ id:"memento", img:"media/galeria_museo/adagios/memento.jpg", pie:"Memento mori: mosaico de Pompeya con calavera y rueda de la fortuna (Museo Arqueológico de Nápoles)", la:"Memento mori", es:"Recuerda que vas a morir.",
  o:"Fórmula tradicional; Tertuliano, Apologético 33, cuenta que en los triunfos romanos se le recordaba al general: «mira detrás de ti; recuerda que eres un hombre»",
  sen:"Recordar la muerte no es para entristecerse, sino para poner las cosas en su sitio y no perder el tiempo en lo que no importa.",
  uso:"Para el estoicismo o el existencialismo (el ser para la muerte de Heidegger).",
  amb:"humano", e:"ant", t:["hf-helenismo", "hf-existencialismo", "fil-t2"] },
{ id:"vitabrevis", img:"media/galeria_museo/adagios/vitabrevis.jpg", pie:"Hipócrates, grabado de Paulus Pontius según Rubens (1638)", la:"Ars longa, vita brevis", gr:"Ὁ βίος βραχύς, ἡ δὲ τέχνη μακρή", tr:"ho bíos brakhýs, he de tékhne makré", es:"La vida es breve; el arte, largo.",
  o:"Hipócrates, Aforismos I, 1; Séneca lo recuerda al empezar Sobre la brevedad de la vida",
  sen:"En Hipócrates, el «arte» es la medicina: hace falta mucho tiempo para dominarla y la vida no alcanza. Séneca responde que la vida no es breve, sino que la desperdiciamos.",
  uso:"Para hablar del tiempo y del uso de la vida (Séneca).",
  amb:"humano", e:"ant", t:["hf-helenismo", "fil-helenismo"] },
{ id:"homosum", img:"media/galeria_museo/adagios/homosum.jpg", pie:"Actores con máscaras en un manuscrito de las comedias de Terencio (siglo IX; Biblioteca Vaticana)", la:"Homo sum, humani nihil a me alienum puto", es:"Soy hombre, y nada de lo humano me es ajeno.",
  o:"Terencio, El atormentador de sí mismo 77",
  sen:"Todo lo que le pasa a cualquier ser humano me concierne. El humanismo del Renacimiento lo leyó como un programa de curiosidad y solidaridad.",
  uso:"Para el humanismo o para el cosmopolitismo.",
  trampa:"En la comedia lo dice un vecino entrometido para justificar que se mete en la vida de otro.",
  amb:"humano", e:"ant", t:["hf-modernidad", "fil-t2"] },
{ id:"ubibene", img:"media/galeria_museo/adagios/ubibene.jpg", pie:"Diógenes, de Jean-Léon Gérôme (1860)", la:"Ubi bene, ibi patria", es:"Donde se está bien, allí está la patria.",
  o:"Cicerón, Tusculanas V, 108, citando un verso de Pacuvio",
  sen:"La patria no es el lugar donde se nace, sino donde se puede vivir bien. Es una idea cosmopolita, cercana a los cínicos y a los estoicos.",
  uso:"Para el cosmopolitismo helenístico o para debatir sobre la identidad.",
  amb:"politica", e:"ant", t:["hf-helenismo", "fil-t6"] },
{ id:"mens", img:"media/galeria_museo/adagios/mens.jpg", pie:"Juvenal coronado de laurel (grabado)", fit:"contain", la:"Mens sana in corpore sano", es:"Mente sana en cuerpo sano.",
  o:"Juvenal, Sátiras X, 356, al final de una sátira sobre lo que la gente pide a los dioses",
  sen:"En Juvenal es una oración: lo único que vale la pena pedir a los dioses es una mente sana en un cuerpo sano, y no riquezas, poder o belleza.",
  uso:"Para hablar de la relación entre cuerpo y alma.",
  trampa:"No es un lema deportivo. Juvenal se burla de lo que la gente pide a los dioses y propone pedir solo lo que de verdad importa.",
  amb:"humano", e:"ant", t:["fil-t2", "hf-antropologia"] },
{ id:"panem", img:"media/galeria_museo/adagios/panem.jpg", pie:"Pollice verso, de Jean-Léon Gérôme (1872)", la:"Panem et circenses", es:"Pan y circo.",
  o:"Juvenal, Sátiras X, 81",
  sen:"El pueblo romano, que antes repartía cargos y legiones, ya solo desea dos cosas: pan y juegos. El poder lo tiene contento con comida y espectáculos.",
  uso:"Para hablar de la manipulación política o de la sociedad del espectáculo.",
  amb:"politica", e:"ant", t:["fil-t6", "hf-siglo21"] },
{ id:"custodes", img:"media/galeria_museo/adagios/custodes.jpg", pie:"El panóptico de Jeremy Bentham (1843): una cárcel en la que un solo vigilante puede verlo todo", fit:"contain", la:"Quis custodiet ipsos custodes?", es:"¿Quién vigilará a los propios vigilantes?",
  o:"Juvenal, Sátiras VI, 347-348",
  sen:"Si alguien tiene que vigilar, ¿quién lo vigila a él? Es la gran pregunta del control del poder.",
  uso:"Para los guardianes de la República de Platón o para la división de poderes.",
  trampa:"En Juvenal no habla de política: se burla de los maridos que ponen guardianes a sus esposas, porque las esposas pueden empezar por los guardianes.",
  amb:"politica", e:"ant", t:["hf-politica", "hf-contrato", "fil-t6"] },
{ id:"duralex", img:"media/galeria_museo/adagios/duralex.jpg", pie:"Antígona ante el cadáver de Polinices, de Nikiforos Lytras (1865)", la:"Dura lex, sed lex", es:"La ley es dura, pero es la ley.",
  o:"Fórmula tradicional; cf. el jurista Ulpiano en el Digesto 40, 9, 12: «es muy duro, pero así está escrita la ley»",
  sen:"La ley obliga aunque nos parezca dura en un caso concreto.",
  uso:"Para el debate entre ley y justicia (Antígona, Sócrates en el Critón).",
  amb:"politica", e:"ant", t:["fil-t6", "fil-t5", "hf-sofistas"] },
{ id:"fiat", img:"media/galeria_museo/adagios/fiat.jpg", pie:"Alegoría de la Justicia, de Giorgio Vasari (1543)", la:"Fiat iustitia, pereat mundus", es:"Hágase justicia, aunque perezca el mundo.",
  o:"Lema del emperador Fernando I (siglo XVI); Kant lo discute en Sobre la paz perpetua (1795), apéndice I",
  sen:"La justicia no se negocia por sus consecuencias. Kant lo traduce así: que se haga justicia aunque perezcan todos los bribones del mundo.",
  uso:"Para la ética del deber frente al utilitarismo.",
  amb:"etica", e:"ren", t:["hf-etica-deber", "hf-kant", "fil-t5"] },
{ id:"fortes", img:"media/galeria_museo/adagios/fortes.jpg", pie:"Némesis o la Gran Fortuna, grabado de Alberto Durero (hacia 1501-1502)", la:"Fortes fortuna adiuvat", es:"La fortuna ayuda a los audaces.",
  o:"Terencio, Formión 203; Maquiavelo lo reelabora en El príncipe XXV",
  sen:"La suerte favorece a quien se atreve. Para Maquiavelo, la fortuna gobierna la mitad de nuestras acciones, y la otra mitad depende de la virtù del gobernante.",
  uso:"Para Maquiavelo: virtù y fortuna.",
  amb:"politica", e:"ant", t:["hf-contrato", "hf-modernidad", "fil-t6"] },
{ id:"cuius", img:"media/galeria_museo/adagios/cuius.jpg", pie:"Documento de la Paz de Augsburgo (1555), con el sello imperial", fit:"contain", la:"Cuius regio, eius religio", es:"A tal territorio, tal religión.",
  o:"Fórmula del jurista Joachim Stephani (hacia 1612) para resumir la Paz de Augsburgo (1555)",
  sen:"Cada príncipe decide la religión de su territorio. Así se pusieron fin a las guerras de religión del Imperio, a costa de la libertad de conciencia de los súbditos.",
  uso:"Para la Reforma protestante y el origen de la tolerancia.",
  amb:"politica", e:"ren", t:["hf-modernidad", "hf-contrato", "fil-t6"] },
{ id:"deussive", img:"media/galeria_museo/adagios/deussive.jpg", pie:"Portada de la Ética de Spinoza en sus obras póstumas (1677)", fit:"contain", la:"Deus sive Natura", es:"Dios, o sea, la Naturaleza.",
  o:"Spinoza, Ética IV, prefacio y proposición 4",
  sen:"Dios no está fuera del mundo: es la única sustancia, y la naturaleza es Dios mismo. Por eso le acusaron de ateo.",
  uso:"Para Spinoza y el debate metafísico moderno.",
  amb:"realidad", e:"mod", t:["hf-metafisica"] }
];
