"use strict";
/* ===== Fichas de época (10-10-2026) =====
   Idea tomada de las «eras» de cerebrofilosofico.com, con contenido propio y comprobado. Una ficha por época de
   Ilustres (ant, med, ren, mod, ilu, con); se abren desde el título de la época en el listado de Ilustres, desde la
   etiqueta de época de cada ficha (#ilustres/epoca-<b>) y desde «La época» al final de los temas de HF.
   Campos: anos (rango), abre (lo que la inaugura), social, politico, ciencia, pensamiento, rupturas (paso a la
   siguiente), trampa (caso trampa). Los pensadores se calculan de ILUSTRES (block). Vista: ilustresview.js.
   Fuentes en #fuentes. Seis fichas: piloto (Ilustración) aprobado el 10-10 y las otras cinco escritas después. */
const EPOCAS_FICHAS = {
 "ant": {
  "anos": "Del siglo VI a. C. al siglo V d. C. (por convención, hasta la caída de Roma en 476).",
  "abre": "<p>En las ciudades griegas de Jonia, como Mileto, unos pensadores empiezan a explicar la naturaleza sin recurrir a los dioses: es el paso <strong>del mito al logos</strong>. Según Heródoto, Tales predijo un eclipse de sol (el de 585 a. C.). Ayudan el comercio, el contacto con Egipto y Babilonia, la escritura alfabética y unas ciudades donde ninguna casta de sacerdotes controla el saber.</p>",
  "social": "<p>La vida gira en torno a la <strong>polis</strong>, la ciudad-estado. Solo los varones libres nacidos en ella son ciudadanos: las mujeres, los extranjeros residentes (metecos) y los esclavos quedan fuera. El tiempo libre para pensar (<em>scholé</em>, de donde viene «escuela») descansa en buena parte sobre el trabajo esclavo. Los niños se educan con los poemas de Homero, y en el siglo V a. C. los sofistas empiezan a cobrar por enseñar a hablar en público.</p>\n<p>Después de Alejandro, el centro del saber se traslada a <strong>Alejandría</strong>, con su Museo y su Biblioteca (siglo III a. C.), y más tarde a Roma, donde la filosofía griega se convierte en parte de la educación de las élites.</p>",
  "politico": "<p>Las polis son independientes y a menudo rivales. Atenas desarrolla la <strong>democracia</strong> tras las reformas de Clístenes (508 a. C.), vence a los persas en las guerras médicas (490-479 a. C.) y pierde la guerra del Peloponeso contra Esparta (431-404 a. C.); poco después condena a muerte a Sócrates (399 a. C.).</p>\n<p>Alejandro Magno crea un imperio enorme (336-323 a. C.) que se divide en reinos helenísticos, y estos acaban absorbidos por <strong>Roma</strong>, república y después imperio (desde el 27 a. C.). En el 380 el cristianismo pasa a ser la religión oficial del Imperio, y en el 476 cae el Imperio romano de Occidente.</p>",
  "ciencia": "<p>Los griegos convierten las técnicas de cálculo de Egipto y Babilonia en <strong>matemáticas demostrativas</strong>: los pitagóricos y, hacia el 300 a. C., los <em>Elementos</em> de Euclides. Eratóstenes calcula la circunferencia de la Tierra (siglo III a. C.); Aristarco propone que la Tierra gira alrededor del Sol, aunque se impondrá el modelo con la Tierra en el centro que Ptolomeo sistematiza en el siglo II. La medicina hipocrática busca causas naturales de las enfermedades, y Aristóteles funda la biología observando animales.</p>\n<p>La técnica, en cambio, avanza poco: con trabajo esclavo abundante, apenas hay interés por ahorrar esfuerzo con máquinas.</p>",
  "pensamiento": "<ul>\n<li><strong>Presocráticos:</strong> buscan el <em>arché</em>, el principio de la naturaleza (<em>physis</em>): agua, aire, números, átomos.</li>\n<li><strong>Giro hacia el ser humano:</strong> los sofistas discuten si las leyes son naturales o convencionales, y Sócrates pregunta qué son la justicia y la virtud.</li>\n<li><strong>Grandes sistemas:</strong> Platón (las Ideas) y Aristóteles (la forma en las cosas) organizan todos los saberes.</li>\n<li><strong>Escuelas helenísticas:</strong> cínicos, epicúreos, estoicos y escépticos se preguntan, sobre todo, cómo vivir con serenidad en un mundo inseguro.</li>\n<li><strong>Final de la época:</strong> el neoplatonismo de Plotino y el encuentro con el cristianismo. Tertuliano preguntó qué tenía que ver Atenas con Jerusalén; otros, como Agustín, harán de la filosofía griega una aliada.</li>\n</ul>",
  "rupturas": "<p>La filosofía antigua no desaparece: el cristianismo la absorbe y la transforma. Agustín de Hipona lee la fe con ojos platónicos. En el 529 el emperador Justiniano prohíbe enseñar filosofía a los paganos en Atenas, y el saber griego sigue vivo sobre todo en Bizancio y, desde el siglo VIII, en el mundo islámico, donde Aristóteles se traduce al árabe y se comenta durante siglos.</p>",
  "trampa": "<p>«Los griegos inventaron la filosofía de la nada.» Bebieron de Egipto y de Babilonia, y no fueron los únicos: en los mismos siglos enseñaban Buda en la India y Confucio en China. Lo propio de los griegos fue convertir la discusión racional y pública en un método. Y otra trampa: la filosofía antigua no son solo Platón y Aristóteles, sino casi doce siglos de escuelas distintas.</p>"
 },
 "med": {
  "anos": "Del siglo V al siglo XV (en el eje del departamento, de 476 a 1492).",
  "abre": "<p>En el 476 cae el Imperio romano de Occidente. En medio de la ruina de las ciudades, la <strong>Iglesia</strong> se convierte en la institución que conserva la escritura, los libros y la enseñanza. Agustín de Hipona, que muere en el 430 mientras los vándalos asedian su ciudad, deja escrita la gran síntesis entre filosofía griega y fe cristiana que guiará los siglos siguientes.</p>",
  "social": "<p>Es una sociedad <strong>estamental</strong>: hacia el año 1000 se la describía como formada por los que rezan, los que combaten y los que trabajan. La mayoría vive en el campo, sometida a un señor (el <strong>feudalismo</strong>). Los monasterios copian y guardan los libros antiguos; los conventos son también uno de los pocos lugares donde las mujeres pueden estudiar y escribir, como Hildegarda de Bingen.</p>\n<p>Desde el siglo XI renacen las ciudades y el comercio, y nacen las <strong>universidades</strong> (Bolonia, París, Oxford, Salamanca). La peste negra (1347-1351) mata a una parte enorme de la población europea, quizá un tercio.</p>",
  "politico": "<p>Tras Roma surgen los reinos germánicos; Carlomagno es coronado emperador en el año 800. Al este sigue el <strong>Imperio bizantino</strong>, y desde el siglo VII el islam se extiende de Arabia a la península ibérica (al-Ándalus, desde el 711). Papas y emperadores se disputan durante siglos quién tiene la última palabra, y las cruzadas (1096-1291) enfrentan a cristianos y musulmanes.</p>\n<p>La época se cierra con dos fechas: la caída de Constantinopla en manos otomanas (1453) y, en 1492, la toma de Granada y la llegada de Colón a América.</p>",
  "ciencia": "<p>En la <strong>Bagdad</strong> de los siglos VIII-X se traducen al árabe Aristóteles, Euclides, Ptolomeo y Galeno. Al-Juarismi da nombre al <strong>álgebra</strong> y al algoritmo; Avicena escribe el <em>Canon de medicina</em>, estudiado en Europa durante siglos. En los siglos XII y XIII, en Toledo y en otros lugares, ese saber se traduce al latín, y Europa adopta los números indoarábigos y el cero.</p>\n<p>La técnica avanza más de lo que se suele creer: el arado pesado, los molinos, el reloj mecánico y, hacia 1450, la <strong>imprenta</strong> de tipos móviles de Gutenberg.</p>",
  "pensamiento": "<ul>\n<li><strong>Fe y razón:</strong> el gran problema de la época es cómo encajar lo que se cree con lo que se demuestra.</li>\n<li><strong>Patrística:</strong> los Padres de la Iglesia, con Agustín a la cabeza, piensan la fe con herramientas platónicas.</li>\n<li><strong>Escolástica:</strong> en las escuelas y universidades se razona con un método riguroso (lectura, cuestión, disputa). Anselmo propone su argumento ontológico; Tomás de Aquino armoniza a Aristóteles con la fe.</li>\n<li><strong>Filosofía en árabe y en hebreo:</strong> Avicena, Averroes y Maimónides piensan los mismos problemas desde el islam y el judaísmo.</li>\n<li><strong>Los universales:</strong> ¿existe «el ser humano» además de cada ser humano? Abelardo y Ockham responden que son nombres o conceptos.</li>\n</ul>",
  "rupturas": "<p>En el siglo XIV, Ockham separa la fe de la razón: lo que se cree no puede demostrarse, y la navaja que lleva su nombre recorta las entidades innecesarias. La peste, el Cisma de Occidente (1378-1417), con dos y hasta tres papas a la vez, y la crítica de los humanistas italianos a la escolástica abren paso al Renacimiento. La imprenta hará el resto.</p>",
  "trampa": "<p>«La Edad Media fue una época oscura.» El nombre lo inventaron los humanistas para despreciarla, pero en ella nacieron las universidades, la lógica alcanzó un nivel muy alto y se tradujo medio saber antiguo. Y no: los sabios medievales no creían que la Tierra fuera plana; su forma esférica se enseñaba en las universidades, por ejemplo con el <em>Tratado de la esfera</em> de Sacrobosco (siglo XIII).</p>"
 },
 "ren": {
  "anos": "De mediados del siglo XV a finales del siglo XVI (en el eje del departamento, de 1492 a 1600).",
  "abre": "<p>Tres novedades cambian el mundo en pocos años: la <strong>imprenta</strong> (hacia 1450), que multiplica los libros; la llegada a Italia de sabios y manuscritos griegos de Bizancio; y la llegada de Colón a América (1492), que demuestra que el mundo conocido por los antiguos era solo una parte.</p>",
  "social": "<p>Las ciudades italianas, como Florencia o Venecia, se enriquecen con el comercio y la banca, y familias como los Médici pagan a artistas y sabios (el <strong>mecenazgo</strong>). Los libros impresos llegan a más gente, y aparece la figura del humanista que vive de escribir, enseñar o aconsejar a los príncipes.</p>\n<p>La conquista de América destruye sociedades enteras y abre el comercio atlántico de personas esclavizadas. También provoca un debate filosófico: en la Junta de Valladolid (1550-1551), Bartolomé de las Casas y Juan Ginés de Sepúlveda discuten si los pueblos indígenas pueden ser sometidos.</p>",
  "politico": "<p>Se forman los <strong>Estados modernos</strong>, con reyes que concentran el poder (los Reyes Católicos, Francia, Inglaterra). Italia, dividida en pequeños estados, es campo de batalla de las grandes potencias: en ese contexto escribe Maquiavelo <em>El príncipe</em> (1513).</p>\n<p>En 1517 Lutero publica sus 95 tesis y comienza la <strong>Reforma</strong> protestante. Europa se divide religiosamente: guerras de religión, la Paz de Augsburgo (1555), que deja a cada príncipe elegir la religión de sus súbditos, y la respuesta católica del Concilio de Trento (1545-1563).</p>",
  "ciencia": "<p>En 1543 aparecen dos libros decisivos: <em>Sobre las revoluciones de las esferas celestes</em> de Copérnico, que pone el Sol en el centro, y la anatomía de Vesalio, que corrige a Galeno a partir de disecciones. Leonardo da Vinci une arte, observación e ingeniería. La <strong>revolución científica</strong> empieza aquí y culminará en el siglo XVII con Kepler, Galileo, Harvey y Newton.</p>",
  "pensamiento": "<ul>\n<li><strong>Humanismo:</strong> vuelta a los textos clásicos en su lengua original y confianza en la dignidad del ser humano, capaz de hacerse a sí mismo (Pico della Mirandola, <em>Discurso sobre la dignidad del hombre</em>, 1486).</li>\n<li><strong>Crítica y tolerancia:</strong> Erasmo se burla de los abusos de su tiempo en el <em>Elogio de la locura</em> (1511) y defiende una religión interior y pacífica.</li>\n<li><strong>Utopías:</strong> Tomás Moro (<em>Utopía</em>, 1516) y, más tarde, Campanella imaginan sociedades justas para criticar las reales.</li>\n<li><strong>Realismo político:</strong> Maquiavelo separa la política de la moral religiosa.</li>\n<li><strong>Una naturaleza infinita:</strong> Nicolás de Cusa y Giordano Bruno, quemado por la Inquisición en 1600, piensan un universo sin límites.</li>\n</ul>",
  "rupturas": "<p>Al final del siglo XVI la autoridad de la Iglesia está dividida y la de Aristóteles, en entredicho. Montaigne duda de casi todo. La pregunta que hereda la Modernidad es dónde encontrar un fundamento seguro para el conocimiento: Francis Bacon propone un método basado en la experiencia (<em>Novum organum</em>, 1620) y Descartes, en la razón (<em>Discurso del método</em>, 1637).</p>\n<p>En Ilustres, Descartes aparece en esta época porque el eje del departamento la cierra en 1600 y él nació en 1596; pero su obra abre la filosofía moderna.</p>",
  "trampa": "<p>«En el Renacimiento la ciencia derrotó a la religión.» Copérnico era canónigo de la Iglesia, y Kepler y Galileo eran creyentes. Además, junto a la nueva ciencia florecieron la magia, la astrología y la alquimia, que muchos humanistas tomaban muy en serio.</p>"
 },
 "mod": {
  "anos": "El siglo XVII (en el eje del departamento, la filosofía moderna va de 1600 a 1800; la Ilustración tiene aquí su propia ficha).",
  "abre": "<p>La <strong>revolución científica</strong> cambia la manera de conocer. Galileo apunta su telescopio al cielo (1610) y defiende que el libro de la naturaleza está escrito en lengua matemática (<em>El ensayador</em>, 1623). Con la autoridad de los antiguos en crisis, Descartes busca empezar de cero, desde una verdad que no se pueda dudar (<em>Discurso del método</em>, 1637).</p>",
  "social": "<p>Es un siglo de crisis: la <strong>guerra de los Treinta Años</strong> (1618-1648) arrasa Europa central, y las epidemias y las malas cosechas son frecuentes. Los Países Bajos, república comercial y relativamente tolerante, acogen a pensadores perseguidos o incómodos: allí vivieron Descartes y Spinoza, a quien su comunidad judía expulsó en 1656.</p>\n<p>Los sabios forman una «república de las letras» que se escribe cartas por toda Europa, como las de Descartes e Isabel de Bohemia, y nacen las primeras <strong>academias científicas</strong>: la Royal Society de Londres (1660) y la Academia de Ciencias de París (1666).</p>",
  "politico": "<p>Triunfa el <strong>absolutismo</strong>: el rey concentra todo el poder, como Luis XIV en Francia (reinó de 1643 a 1715). La Paz de Westfalia (1648) organiza Europa en Estados soberanos. Inglaterra es la excepción: una guerra civil (1642-1651) termina con la ejecución del rey Carlos I en 1649, y la Revolución Gloriosa (1688-1689) limita el poder de la corona. Hobbes escribe el <em>Leviatán</em> (1651) tras la guerra; Locke, sus <em>Dos tratados sobre el gobierno civil</em> (1689) tras la revolución.</p>",
  "ciencia": "<p>Kepler descubre que los planetas giran en elipses; Harvey demuestra la circulación de la sangre (1628); el microscopio revela un mundo invisible (Hooke, <em>Micrographia</em>, 1665). Newton y Leibniz inventan por separado el <strong>cálculo infinitesimal</strong>, y Newton une la física del cielo y la de la Tierra en una sola ley de la gravedad (1687).</p>\n<p>La imagen dominante es el <strong>mecanicismo</strong>: el mundo funciona como un gran reloj, con piezas que se mueven por contacto según leyes matemáticas.</p>",
  "pensamiento": "<ul>\n<li><strong>El método y la certeza:</strong> antes de saber qué hay, hay que saber cómo podemos conocerlo.</li>\n<li><strong>Racionalismo:</strong> Descartes, Spinoza, Malebranche y Leibniz confían en ideas que la razón conoce por sí misma.</li>\n<li><strong>Empirismo:</strong> Locke y Berkeley sostienen que todo conocimiento procede de la experiencia; Hume lo llevará al límite en el siglo siguiente.</li>\n<li><strong>Sustancia:</strong> ¿cuántas hay? Dos para Descartes (mente y materia), una para Spinoza, infinitas mónadas para Leibniz, solo materia para Hobbes.</li>\n<li><strong>Contrato social y tolerancia:</strong> Hobbes y Locke fundan el poder en un pacto; Spinoza (1670) y Locke (1689) defienden la libertad de pensamiento y la tolerancia religiosa.</li>\n</ul>",
  "rupturas": "<p>Newton y Locke se convierten en los modelos de la generación siguiente: Voltaire los da a conocer en Francia en sus <em>Cartas filosóficas</em> (1734). La confianza en la razón, que el siglo XVII aplicó sobre todo a la naturaleza, la Ilustración la extenderá a la sociedad, la política y la religión.</p>",
  "trampa": "<p>«Racionalistas y empiristas eran dos equipos enfrentados.» La etiqueta la pusieron después los historiadores. Todos se leían y se respondían: Locke discute con Descartes, y Leibniz dedicó un libro entero a contestar a Locke (<em>Nuevos ensayos sobre el entendimiento humano</em>). Y casi todos compartían la confianza en las matemáticas y en la nueva física.</p>"
 },
 "ilu": {
  "anos": "De finales del siglo XVII (hacia 1680) a 1800, aproximadamente.",
  "abre": "<p>La revolución científica culmina con los <em>Principios matemáticos de la filosofía natural</em> de Newton (1687): el universo obedece a leyes que la razón puede descubrir. Al año siguiente, la Revolución Gloriosa inglesa (1688-1689) somete al rey a una declaración de derechos del Parlamento. Razón y libertad política son las dos ideas que la época llevará más lejos.</p>",
  "social": "<p>Crece una <strong>burguesía</strong> de comerciantes, médicos, abogados y funcionarios que lee, discute y quiere influir. Nacen lugares de conversación fuera de la corte y de la Iglesia: los <strong>cafés</strong>, las academias, las logias y los <strong>salones</strong>, muchos dirigidos por mujeres, como el de Madame Geoffrin en París. Se multiplican los periódicos y los libros baratos, y aparece algo nuevo: la <strong>opinión pública</strong>.</p>\n<p>Pero la Ilustración fue cosa de minorías: la mayoría de la población era campesina y no sabía leer. Y la riqueza de los puertos europeos dependía en buena parte del comercio atlántico de personas esclavizadas.</p>",
  "politico": "<p>Casi toda Europa vive en <strong>monarquías absolutas</strong>. Algunos reyes adoptan reformas ilustradas sin ceder poder (el llamado <strong>despotismo ilustrado</strong>: Federico II de Prusia, Catalina II de Rusia, Carlos III en España). La censura sigue activa: la <em>Enciclopedia</em> fue prohibida en Francia en 1759 y siguió publicándose a escondidas.</p>\n<p>Al final del siglo, dos revoluciones llevan las ideas a la política: la <strong>independencia de los Estados Unidos</strong> (1776), con su declaración de derechos, y la <strong>Revolución francesa</strong> (1789), con la <em>Declaración de los derechos del hombre y del ciudadano</em>.</p>",
  "ciencia": "<p>Newton se convierte en el modelo de todo saber: observar, medir y buscar leyes. Linneo clasifica los seres vivos (<em>Sistema de la naturaleza</em>, 1735); Lavoisier funda la química moderna (<em>Tratado elemental de química</em>, 1789); Jenner prueba la primera vacuna, contra la viruela (1796). En Gran Bretaña, la máquina de vapor de Watt (patentada en 1769) abre la <strong>Revolución industrial</strong>.</p>\n<p>La <em>Enciclopedia</em> de Diderot y d'Alembert (1751-1772) quiere reunir todo el saber, también el de los oficios, con láminas de talleres y máquinas: el conocimiento técnico pasa a ser digno de la filosofía.</p>",
  "pensamiento": "<p>La idea central la resumió Kant en 1784: la Ilustración es la salida del ser humano de una minoría de edad de la que él mismo es culpable; su lema, <em>sapere aude</em>, «¡ten el valor de servirte de tu propio entendimiento!» (<em>¿Qué es la Ilustración?</em>). De ahí sus grandes rasgos:</p>\n<ul>\n<li><strong>Razón crítica:</strong> nada se acepta por tradición o autoridad sin examinarlo, ni siquiera la propia razón (Hume, Kant).</li>\n<li><strong>Progreso:</strong> el saber y la educación pueden mejorar la vida humana (Rousseau, <em>Emilio</em>, 1762).</li>\n<li><strong>Tolerancia</strong> religiosa y crítica de la superstición (Voltaire, <em>Tratado sobre la tolerancia</em>, 1763). Muchos ilustrados son deístas: creen en un Dios creador, pero no en las religiones reveladas.</li>\n<li><strong>Derechos y división de poderes</strong> frente al absolutismo (Montesquieu, <em>El espíritu de las leyes</em>, 1748; Rousseau, <em>El contrato social</em>, 1762).</li>\n<li><strong>Felicidad y utilidad:</strong> la moral se piensa desde el sentimiento (Hume) o desde las consecuencias (Bentham), y la economía como un saber propio (Adam Smith, <em>La riqueza de las naciones</em>, 1776).</li>\n<li>Primeras voces por la <strong>igualdad de las mujeres</strong>: Olympe de Gouges (1791) y Mary Wollstonecraft (1792).</li>\n</ul>",
  "rupturas": "<p>La Ilustración no termina de golpe. En Alemania, Hamann y Herder le reprochan olvidar el sentimiento, la lengua y la historia de cada pueblo, y el <strong>Romanticismo</strong> recoge esa crítica. El Terror de la Revolución francesa (1793-1794) hace preguntarse si la razón puede rehacer una sociedad entera. Kant cierra la época y la examina a la vez: sus <em>Críticas</em> marcan los límites de la razón.</p>\n<p>Otras líneas siguen en el siglo XIX: el <strong>utilitarismo</strong> y el <strong>liberalismo</strong> de Bentham y Mill (por eso en Ilustres van en esta época), y la fe en el progreso, que heredan Hegel y Marx. En el siglo XX, Adorno y Horkheimer (<em>Dialéctica de la Ilustración</em>, 1944) se preguntan por qué la razón ilustrada no impidió la barbarie.</p>",
  "trampa": "<p>«La Ilustración fue francesa.» París fue su capital más visible, pero hubo una Ilustración escocesa (Hume, Smith), una alemana (Kant, Lessing, Mendelssohn), una española (Feijoo, Jovellanos) y una americana (Franklin, Jefferson). Y «ilustrado» no quiere decir «ateo»: Holbach lo era, pero Voltaire era deísta y Kant defendía una fe racional.</p>"
 },
 "con": {
  "anos": "Del siglo XIX a hoy (en el eje del departamento, desde 1800).",
  "abre": "<p>La Revolución francesa y las guerras de Napoleón cambian el mapa político de Europa, y la <strong>Revolución industrial</strong> cambia la manera de vivir y de trabajar. En filosofía, Kant ha dejado abierta la pregunta por los límites de la razón, y el idealismo alemán intenta superarlos: Hegel publica la <em>Fenomenología del espíritu</em> en 1807.</p>",
  "social": "<p>Las fábricas atraen a millones de personas del campo a las ciudades. Nace el <strong>proletariado</strong>, con jornadas larguísimas y trabajo infantil, como describen las novelas de Dickens, y con él el movimiento obrero, los sindicatos y los socialismos. En el siglo XX llegan la sociedad de masas, el consumo, la radio y la televisión; las mujeres conquistan el voto (Nueva Zelanda en 1893, España en 1931) y la escuela llega a casi todos.</p>\n<p>Hoy vivimos en un mundo <strong>globalizado</strong> y conectado por internet, con desigualdades enormes y una crisis ecológica que obliga a repensar el progreso.</p>",
  "politico": "<p>El siglo XIX es el de las revoluciones liberales (1830, 1848), los nacionalismos y los imperios coloniales. El XX, el de las dos <strong>guerras mundiales</strong> (1914-1918 y 1939-1945), los totalitarismos (fascismo, nazismo, estalinismo) y el Holocausto. Tras 1945 nacen la ONU y la Declaración Universal de los Derechos Humanos (1948), comienza la Guerra Fría y se descolonizan Asia y África.</p>\n<p>En España, la dictadura franquista (1939-1975) lleva al exilio a muchos pensadores, como María Zambrano. La caída del muro de Berlín (1989) cierra la Guerra Fría.</p>",
  "ciencia": "<p>Darwin explica la evolución de las especies (<em>El origen de las especies</em>, 1859) y Mendel descubre las leyes de la herencia; en 1953 se describe la estructura del ADN, con datos de Rosalind Franklin. Freud explora el inconsciente. Einstein (relatividad) y la mecánica cuántica cambian la física; Frege y Russell renuevan la lógica, y Turing (1936) y Shannon (1948) ponen las bases de la informática. Llegan la energía nuclear, internet y la inteligencia artificial.</p>",
  "pensamiento": "<ul>\n<li><strong>Idealismo y positivismo:</strong> Hegel piensa la historia como el despliegue de la razón; Comte, que el saber culmina en la ciencia positiva.</li>\n<li><strong>Maestros de la sospecha:</strong> Marx, Nietzsche y Freud buscan detrás de las ideas los intereses económicos, la voluntad de poder o el deseo inconsciente.</li>\n<li><strong>Existencia y fenomenología:</strong> Heidegger, Sartre, Beauvoir y Camus parten de la existencia concreta, la libertad y la angustia.</li>\n<li><strong>Giro lingüístico:</strong> Wittgenstein y la filosofía analítica examinan el lenguaje; Popper y Kuhn, la ciencia.</li>\n<li><strong>Teoría crítica:</strong> la Escuela de Fráncfort (Horkheimer, Adorno, Habermas) analiza la sociedad de masas.</li>\n<li><strong>Filosofía en España:</strong> Unamuno, Ortega y Zambrano; en euskera, Txillardegi y Azurmendi.</li>\n<li><strong>Debates de hoy:</strong> feminismo (Beauvoir, Butler), posmodernidad (Lyotard, Foucault, Derrida), justicia (Rawls), ecología (Yayo Herrero), tecnología y mente (Han, Bostrom, Chalmers).</li>\n</ul>",
  "rupturas": "<p>Es una época que no ha terminado, con varios cortes internos. La Primera Guerra Mundial rompe la fe del siglo XIX en el progreso; Auschwitz e Hiroshima obligan a preguntar qué ha hecho la razón (Adorno, Arendt); en 1979, Lyotard anuncia el fin de los «grandes relatos». Las preguntas abiertas hoy, como la inteligencia artificial, la crisis climática o la desinformación, quizá estén abriendo ya otra época que todavía no sabemos nombrar.</p>",
  "trampa": "<p>«Contemporáneo quiere decir de hoy.» En historia, la Edad Contemporánea empieza a finales del siglo XVIII: Hegel y Marx son filósofos «contemporáneos» aunque vivieran hace dos siglos. Y otra trampa: que la filosofía actual sea muy diversa no significa que todo valga; cada corriente discute con razones con las demás.</p>"
 }
};
