"use strict";
/* ===== Genealogías · «Red de tesis» (09-10) =====
   Inspirada en «History of Philosophy — Summarized & Visualized» (Deniz Cem Önduygu): no se enlazan autores,
   sino TESIS. Cada tesis es una frase con su referencia (obra y lugar canónico) y su forma: «literal»,
   «paráfrasis» o «fórmula tradicional» (no literal del autor). Los enlaces dicen si dos tesis concuerdan
   (verde) o se oponen (rojo) y POR QUÉ; las relaciones son discutibles a propósito: discutirlas es el ejercicio.
   tesis: {id, ilustre (id de ILUSTRES; no se traduce), t, ref, forma}
   enlaces: {k:"idTesisA|idTesisB" (no se traduce), tipo:"acuerdo"|"desacuerdo" (no se traduce), por}
   Vista: genealogiasview.js (modo «Red de tesis»). */
const GEN_TESIS = {
 tesis: [
  { id: "her-flujo", ilustre: "heraclito", t: "Todo fluye: no es posible bañarse dos veces en el mismo río.", ref: "Fragmento DK 22 B 91 (Plutarco); «todo fluye» (panta rhei) es la fórmula con que la tradición lo resume", forma: "fórmula tradicional" },
  { id: "par-ser", ilustre: "parmenides", t: "El ser es y el no ser no es: el cambio y la multiplicidad son apariencia.", ref: "Poema, fragmentos DK 28 B 2 y B 8", forma: "paráfrasis" },
  { id: "pro-medida", ilustre: "protagoras", t: "El hombre es la medida de todas las cosas.", ref: "Fragmento DK 80 B 1, citado por Platón, Teeteto 152a", forma: "literal" },
  { id: "soc-examen", ilustre: "socrates", t: "Una vida sin examen no merece ser vivida.", ref: "Platón, Apología de Sócrates 38a", forma: "literal" },
  { id: "soc-virtud", ilustre: "socrates", t: "Nadie obra mal a sabiendas: la virtud es conocimiento.", ref: "Platón, Protágoras 345d-e y 358c-d (intelectualismo moral)", forma: "paráfrasis" },
  { id: "pla-ideas", ilustre: "platon", t: "Las Ideas, eternas e inmutables, son la verdadera realidad; lo sensible es solo su copia.", ref: "República VII 514a-517c (la caverna); Fedón 74a-75d", forma: "paráfrasis" },
  { id: "pla-anam", ilustre: "platon", t: "Conocer es recordar lo que el alma contempló antes de nacer.", ref: "Menón 81c-d; Fedón 72e-76e (anámnesis)", forma: "paráfrasis" },
  { id: "pla-rey", ilustre: "platon", t: "No habrá fin de los males en las ciudades hasta que los filósofos gobiernen o los gobernantes filosofen.", ref: "República V 473c-d", forma: "paráfrasis" },
  { id: "ari-forma", ilustre: "aristoteles", t: "No hay Ideas separadas: la forma está en las cosas mismas, unida a la materia.", ref: "Metafísica I 9 (990b-991b) y VII", forma: "paráfrasis" },
  { id: "ari-exp", ilustre: "aristoteles", t: "Todo conocimiento comienza en la percepción sensible: de ella nacen la memoria y la experiencia.", ref: "Metafísica I 1 (980a-981a); Analíticos segundos II 19 (100a)", forma: "paráfrasis" },
  { id: "ari-habito", ilustre: "aristoteles", t: "La virtud ética no se enseña como una ciencia: se adquiere por hábito, practicando.", ref: "Ética a Nicómaco II 1 (1103a14-b25)", forma: "paráfrasis" },
  { id: "ari-polis", ilustre: "aristoteles", t: "El ser humano es por naturaleza un animal político.", ref: "Política I 2 (1253a2-3)", forma: "literal" },
  { id: "epi-placer", ilustre: "epicuro", t: "El placer es el principio y el fin de la vida feliz.", ref: "Carta a Meneceo 128-129", forma: "literal" },
  { id: "agu-interior", ilustre: "agustin", t: "No salgas fuera, vuelve a ti mismo: en el interior del hombre habita la verdad.", ref: "De la verdadera religión 39, 72", forma: "literal" },
  { id: "agu-creer", ilustre: "agustin", t: "Cree para entender y entiende para creer.", ref: "Sermón 43, 7, 9", forma: "paráfrasis" },
  { id: "tom-armonia", ilustre: "tomas", t: "La razón y la fe no pueden contradecirse, porque las dos proceden de Dios.", ref: "Suma contra los gentiles I 7", forma: "paráfrasis" },
  { id: "tom-vias", ilustre: "tomas", t: "La existencia de Dios se demuestra a partir de sus efectos en el mundo sensible (las cinco vías).", ref: "Suma de teología I, q. 2, a. 3", forma: "paráfrasis" },
  { id: "ock-navaja", ilustre: "ockham", t: "No hay que multiplicar los entes sin necesidad.", ref: "«Navaja de Ockham»; en sus obras: «no se ha de poner pluralidad sin necesidad» (Ordinatio I, d. 30, q. 1)", forma: "fórmula tradicional" },
  { id: "ock-univ", ilustre: "ockham", t: "Los universales no existen fuera de la mente: son signos que significan muchas cosas singulares.", ref: "Suma de lógica I 14-15", forma: "paráfrasis" },
  { id: "des-cogito", ilustre: "descartes", t: "Pienso, luego existo.", ref: "Discurso del método IV (AT VI 32)", forma: "literal" },
  { id: "des-innatas", ilustre: "descartes", t: "Hay ideas innatas, como la de Dios, que no proceden de los sentidos.", ref: "Meditaciones metafísicas III (AT VII 37-38 y 51)", forma: "paráfrasis" },
  { id: "des-dual", ilustre: "descartes", t: "El alma y el cuerpo son dos sustancias distintas: una piensa y la otra es extensa.", ref: "Meditaciones metafísicas VI (AT VII 78)", forma: "paráfrasis" },
  { id: "hob-guerra", ilustre: "hobbes", t: "Sin un poder común que los atemorice, los hombres viven en guerra de todos contra todos, y la vida es solitaria, pobre, desagradable, brutal y corta.", ref: "Leviatán I 13", forma: "paráfrasis" },
  { id: "loc-tabla", ilustre: "locke", t: "No hay ideas innatas: al principio la mente es como un papel en blanco y todo le llega de la experiencia.", ref: "Ensayo sobre el entendimiento humano I y II 1, § 2", forma: "paráfrasis" },
  { id: "loc-resistir", ilustre: "locke", t: "El gobierno existe para proteger la vida, la libertad y la propiedad; si las viola, el pueblo puede resistirle.", ref: "Segundo tratado sobre el gobierno civil §§ 123-131 y 222", forma: "paráfrasis" },
  { id: "hum-impr", ilustre: "hume", t: "Todas nuestras ideas son copias de impresiones.", ref: "Investigación sobre el entendimiento humano, sección II", forma: "paráfrasis" },
  { id: "hum-causa", ilustre: "hume", t: "La conexión necesaria entre causa y efecto no se percibe: la esperamos por costumbre.", ref: "Investigación sobre el entendimiento humano, secciones V y VII", forma: "paráfrasis" },
  { id: "hum-esclava", ilustre: "hume", t: "La razón es, y solo debe ser, esclava de las pasiones.", ref: "Tratado de la naturaleza humana II, 3, 3", forma: "literal" },
  { id: "rou-bueno", ilustre: "rousseau", t: "El ser humano es bueno por naturaleza: la sociedad lo corrompe.", ref: "Fórmula que resume el Discurso sobre el origen de la desigualdad y el comienzo del Emilio («todo degenera entre las manos del hombre»)", forma: "fórmula tradicional" },
  { id: "kan-sapere", ilustre: "kant", t: "Ilustración es la salida del hombre de su minoría de edad: ¡ten el valor de servirte de tu propio entendimiento!", ref: "Respuesta a la pregunta: ¿qué es la Ilustración? (1784), AA VIII 35", forma: "literal" },
  { id: "kan-exp", ilustre: "kant", t: "Aunque todo nuestro conocimiento comience con la experiencia, no por eso procede todo él de la experiencia.", ref: "Crítica de la razón pura, Introducción, B 1", forma: "literal" },
  { id: "kan-ley", ilustre: "kant", t: "Obra solo según aquella máxima por la cual puedas querer al mismo tiempo que se convierta en ley universal.", ref: "Fundamentación de la metafísica de las costumbres, AA IV 421", forma: "literal" },
  { id: "kan-mentir", ilustre: "kant", t: "No es lícito mentir, ni siquiera al asesino que pregunta dónde se esconde tu amigo.", ref: "Sobre un presunto derecho a mentir por filantropía (1797), AA VIII 425-430", forma: "paráfrasis" },
  { id: "mil-util", ilustre: "mill", t: "Las acciones son correctas en la medida en que tienden a promover la felicidad, e incorrectas si producen lo contrario.", ref: "El utilitarismo, cap. II", forma: "paráfrasis" },
  { id: "mil-socrates", ilustre: "mill", t: "Es mejor ser un Sócrates insatisfecho que un necio satisfecho.", ref: "El utilitarismo, cap. II", forma: "literal" },
  { id: "mar-conciencia", ilustre: "marx", t: "No es la conciencia la que determina el ser, sino el ser social el que determina la conciencia.", ref: "Contribución a la crítica de la economía política (1859), Prólogo", forma: "literal" },
  { id: "mar-tesis", ilustre: "marx", t: "Los filósofos no han hecho más que interpretar el mundo de diversos modos; de lo que se trata es de transformarlo.", ref: "Tesis sobre Feuerbach, XI", forma: "literal" },
  { id: "nie-dios", ilustre: "nietzsche", t: "Dios ha muerto, y nosotros lo hemos matado.", ref: "La gaya ciencia § 125 («El loco»)", forma: "literal" },
  { id: "nie-fabula", ilustre: "nietzsche", t: "El «mundo verdadero» es una fábula: no hay otro mundo detrás del que vivimos.", ref: "Crepúsculo de los ídolos, «Cómo el “mundo verdadero” acabó convirtiéndose en una fábula»", forma: "paráfrasis" },
  { id: "nie-socrates", ilustre: "nietzsche", t: "Sócrates es un síntoma de decadencia: oponer la razón a los instintos es enfermar.", ref: "Crepúsculo de los ídolos, «El problema de Sócrates»", forma: "paráfrasis" },
  { id: "ort-circ", ilustre: "ortega", t: "Yo soy yo y mi circunstancia, y si no la salvo a ella no me salvo yo.", ref: "Meditaciones del Quijote (1914), «Lector…»", forma: "literal" },
  { id: "sar-exist", ilustre: "sartre", t: "La existencia precede a la esencia: el ser humano no es otra cosa que lo que él se hace.", ref: "El existencialismo es un humanismo (1946)", forma: "literal" },
  { id: "bea-mujer", ilustre: "beauvoir", t: "No se nace mujer: se llega a serlo.", ref: "El segundo sexo, vol. II, primera parte, cap. I", forma: "literal" }
 ],
 enlaces: [
  { k: "her-flujo|par-ser", tipo: "desacuerdo", por: "Para Heráclito la realidad es cambio; para Parménides el cambio es imposible y solo es apariencia. Es la primera gran oposición de la filosofía." },
  { k: "par-ser|pla-ideas", tipo: "acuerdo", por: "Platón hereda de Parménides que lo verdadero es inmutable y se alcanza con la razón, no con los sentidos: lo sitúa en las Ideas." },
  { k: "her-flujo|pla-ideas", tipo: "acuerdo", por: "Platón acepta que lo sensible fluye sin cesar, como decía Heráclito (así lo cuenta Aristóteles, Metafísica I 6); por eso busca la verdad fuera de lo sensible. Concuerdan en el diagnóstico, no en la salida." },
  { k: "pro-medida|pla-ideas", tipo: "desacuerdo", por: "Si cada uno es la medida, no hay verdad común; Platón dedica el Teeteto a refutarlo: si todo es verdad para quien lo cree, también lo es que Protágoras se equivoca." },
  { k: "soc-virtud|ari-habito", tipo: "desacuerdo", por: "Aristóteles critica el intelectualismo socrático: se puede saber qué es lo bueno y no hacerlo (la akrasía); la virtud necesita hábito, no solo conocimiento (Ética a Nicómaco VII 2-3)." },
  { k: "pla-ideas|ari-forma", tipo: "desacuerdo", por: "La gran discusión entre maestro y discípulo: para Aristóteles, unas Ideas separadas duplican el mundo sin explicarlo." },
  { k: "pla-anam|ari-exp", tipo: "desacuerdo", por: "Para Platón conocer es recordar lo que el alma ya sabía; para Aristóteles el conocimiento se construye desde la percepción." },
  { k: "pla-anam|des-innatas", tipo: "acuerdo", por: "Descartes, como Platón, defiende que hay conocimientos que no vienen de los sentidos, sino que la mente ya trae consigo." },
  { k: "ari-forma|des-dual", tipo: "desacuerdo", por: "Para Aristóteles el alma es la forma del cuerpo y no existe separada de él (Acerca del alma II 1); Descartes las convierte en dos sustancias distintas, y nace el problema de cómo se comunican." },
  { k: "des-innatas|loc-tabla", tipo: "desacuerdo", por: "El primer libro del Ensayo de Locke es un ataque a las ideas innatas: la mente empieza vacía." },
  { k: "loc-tabla|hum-impr", tipo: "acuerdo", por: "Hume radicaliza el empirismo de Locke: si todo viene de la experiencia, cada idea debe poder rastrearse hasta una impresión." },
  { k: "hum-causa|kan-exp", tipo: "desacuerdo", por: "Kant reconoce que Hume lo despertó de su «sueño dogmático», pero no acepta que la causalidad sea solo costumbre: es una condición a priori de toda experiencia posible." },
  { k: "ari-exp|kan-exp", tipo: "acuerdo", por: "Los dos ponen el comienzo del conocimiento en la experiencia sensible; Kant añade que no todo procede de ella." },
  { k: "pla-ideas|agu-interior", tipo: "acuerdo", por: "Agustín cristianiza el platonismo: la verdad inmutable no está fuera, en lo sensible, sino que se encuentra volviendo al interior, donde ilumina Dios." },
  { k: "agu-creer|tom-armonia", tipo: "acuerdo", por: "Los dos defienden que fe y razón colaboran. Tomás distingue mejor sus campos: hay verdades que la razón alcanza sola y otras que solo conoce la fe." },
  { k: "ari-exp|tom-vias", tipo: "acuerdo", por: "Tomás demuestra a Dios a la manera aristotélica: desde los efectos sensibles (movimiento, causas, contingencia…) hasta su causa primera." },
  { k: "pla-ideas|ock-univ", tipo: "desacuerdo", por: "Frente al realismo de las Ideas, Ockham sostiene que solo existen individuos: lo universal es un nombre o signo de la mente (nominalismo)." },
  { k: "ock-navaja|pla-ideas", tipo: "desacuerdo", por: "La navaja de Ockham sirve para afeitar entidades innecesarias, y un mundo de Ideas separado es el ejemplo clásico de lo que sobra." },
  { k: "tom-vias|nie-dios", tipo: "desacuerdo", por: "Para Tomás, Dios es la causa primera que la razón alcanza; para Nietzsche, la cultura europea ya no puede apoyarse en Dios, y eso cambia todos los valores." },
  { k: "ari-polis|hob-guerra", tipo: "desacuerdo", por: "Hobbes rechaza que seamos sociables por naturaleza: nos unimos por miedo y por interés, mediante un pacto, y no por una inclinación natural a la polis." },
  { k: "hob-guerra|rou-bueno", tipo: "desacuerdo", por: "Rousseau acusa a Hobbes de atribuir al hombre natural los vicios que en realidad produce la sociedad." },
  { k: "hob-guerra|loc-resistir", tipo: "desacuerdo", por: "Para Hobbes el soberano debe tener un poder absoluto para evitar la guerra; para Locke el poder es limitado y, si traiciona su fin, el pueblo puede resistirle." },
  { k: "soc-virtud|hum-esclava", tipo: "desacuerdo", por: "Para Sócrates saber el bien basta para hacerlo; para Hume la razón sola nunca mueve a actuar: son las pasiones las que deciden." },
  { k: "hum-esclava|kan-ley", tipo: "desacuerdo", por: "Kant defiende una razón práctica que, por sí sola, puede determinar la voluntad mediante una ley moral; para Hume eso es imposible." },
  { k: "kan-ley|mil-util", tipo: "desacuerdo", por: "Para Kant la moralidad está en el deber y en la máxima; para Mill, en las consecuencias para la felicidad. Es la oposición central entre éticas del deber y de la utilidad." },
  { k: "kan-mentir|mil-util", tipo: "desacuerdo", por: "Si cuentan las consecuencias, mentir al asesino salva una vida y es correcto; para Kant el deber de veracidad no depende de las consecuencias." },
  { k: "epi-placer|mil-socrates", tipo: "acuerdo", por: "Mill defiende a los epicúreos de quienes llaman a su ética «doctrina de cerdos»: el placer es el bien, y los placeres del intelecto, los sentimientos y la imaginación valen más que los del cuerpo, como ya sostenían los propios epicúreos." },
  { k: "kan-sapere|soc-examen", tipo: "acuerdo", por: "Pensar por uno mismo y examinar la propia vida: la Ilustración retoma el ideal socrático de no aceptar nada sin examen." },
  { k: "des-cogito|mar-conciencia", tipo: "desacuerdo", por: "Descartes parte de una conciencia que se conoce a sí misma antes que el mundo; para Marx la conciencia es producto de las condiciones materiales y sociales." },
  { k: "mar-tesis|pla-rey", tipo: "desacuerdo", por: "Platón quiere que gobierne quien contempla la verdad; Marx critica la filosofía que solo contempla e interpreta: lo que importa es la praxis que transforma." },
  { k: "pla-ideas|nie-fabula", tipo: "desacuerdo", por: "Nietzsche lee la historia de la filosofía como la historia de un error que empieza en Platón: inventar un «mundo verdadero» y despreciar el que vivimos." },
  { k: "soc-examen|nie-socrates", tipo: "desacuerdo", por: "Lo que para Sócrates es la única vida digna, examinarlo todo con la razón, es para Nietzsche un síntoma de vida enferma." },
  { k: "nie-dios|sar-exist", tipo: "acuerdo", por: "Si no hay Dios que haya pensado una naturaleza humana, como un artesano piensa su obra, el ser humano no tiene esencia previa: se hace a sí mismo." },
  { k: "sar-exist|bea-mujer", tipo: "acuerdo", por: "Beauvoir aplica el existencialismo a la condición femenina: ser mujer no es una esencia natural, sino una situación construida." },
  { k: "des-cogito|ort-circ", tipo: "desacuerdo", por: "Ortega critica el idealismo moderno: el yo no es una conciencia aislada que luego busca el mundo, sino que siempre es yo-con-mi-circunstancia." }
 ]
};
