"use strict";
/* ===== «Rescritura» (09-10, Bachillerato: Filosofía 1.º y HF) =====
   Datos de rescrituraview.js (#rescritura/distinguir|escribir[/texto]). Cada texto: un fragmento clásico (versión propia
   a partir del original, de dominio público), los términos técnicos que se pueden conservar y cuatro versiones, una de
   cada tipo (rescritura, copia, sinonimia, malinterpretación), con la explicación de por qué lo es. La versión de tipo
   «rescritura» sirve también de modelo en «Escribe la tuya». En euskera cada versión está escrita para el original en
   euskera (la copia copia, la sinonimia calca la estructura), no traducida palabra por palabra. */

const RESCRITURA_TIPOS = {
  rescritura: { nombre: "Rescritura", def: "Dice lo mismo que el original, pero con una estructura y unas palabras propias. Conserva los términos técnicos del autor y no añade ni quita ideas importantes." },
  copia: { nombre: "Copia", def: "Repite frases o trozos enteros del original, aunque cambie alguna palabra, quite otras o junte frases (el «mosaico»). Sin comillas, es hacer pasar por tuyo lo que no lo es." },
  sinonimia: { nombre: "Sinonimia", def: "Cambia palabras por sinónimos, pero mantiene el mismo esqueleto: las mismas frases, en el mismo orden. Parece distinto y es el mismo texto disfrazado; además, al cambiar los términos técnicos suele desfigurar el sentido." },
  malinterpretacion: { nombre: "Malinterpretación", def: "Usa palabras propias, pero dice otra cosa: invierte la idea, añade lo que el texto no dice, quita una condición o exagera." }
};

const RESCRITURA_TEXTOS = [
  { id: "kant", autor: "Immanuel Kant", obra: "<em>Respuesta a la pregunta: ¿Qué es la Ilustración?</em> (1784)",
    original: "La Ilustración es la salida del ser humano de su minoría de edad, de la que él mismo es culpable. Minoría de edad es la incapacidad de servirse del propio entendimiento sin la guía de otro. Uno mismo es culpable de ella cuando su causa no está en la falta de entendimiento, sino en la falta de decisión y de valor para servirse de él sin la guía de otro.",
    terminos: ["Ilustración", "minoría de edad", "entendimiento"],
    versiones: [
      { tipo: "rescritura", texto: "Para Kant, ilustrarse consiste en dejar de depender de otros para pensar. Esa dependencia, que él llama minoría de edad, casi nunca se debe a que nos falte inteligencia: se debe a que no nos atrevemos a usarla por nuestra cuenta. Por eso somos responsables de seguir en ella.",
        porque: "Cambia el orden y la manera de decirlo, conserva el término técnico «minoría de edad» y mantiene las tres ideas: qué es la Ilustración, qué es la minoría de edad y por qué somos culpables de ella." },
      { tipo: "copia", texto: "La Ilustración es la salida del hombre de su minoría de edad, de la que él mismo es culpable. La minoría de edad es la incapacidad de servirse de su propio entendimiento sin la guía de otro, y uno es culpable cuando la causa no es la falta de entendimiento, sino de decisión y valor.",
        porque: "Repite frases enteras del original casi palabra por palabra: solo cambia «ser humano» por «hombre» y junta dos frases en una." },
      { tipo: "sinonimia", texto: "La Ilustración es el abandono por parte del hombre de su infancia, de la que él mismo es responsable. Infancia es la imposibilidad de usar la propia razón sin la dirección de otro. Uno mismo es responsable de ella cuando su origen no reside en la carencia de razón, sino en la carencia de resolución y de coraje para usarla sin la dirección de otro.",
        porque: "Cada palabra se cambia por un sinónimo, pero las frases son las mismas y van en el mismo orden. Además, al cambiar «minoría de edad» por «infancia» se pierde la idea de Kant: un menor de edad es alguien que, por ley, necesita un tutor." },
      { tipo: "malinterpretacion", texto: "Kant dice que la mayoría de la gente no es capaz de pensar por sí misma porque no es lo bastante inteligente, y que por eso necesita que alguien con más conocimientos la guíe: la Ilustración consiste en que los sabios eduquen al pueblo.",
        porque: "Dice lo contrario del texto. Para Kant, la causa no es la falta de inteligencia, sino de valor, y la Ilustración es dejar de necesitar la guía de otro, no ponerse bajo la guía de los sabios." }
    ] },

  { id: "descartes", autor: "René Descartes", obra: "<em>Discurso del método</em>, primera parte (1637)",
    original: "El buen sentido es la cosa mejor repartida del mundo, pues cada uno piensa estar tan bien provisto de él que incluso los más difíciles de contentar en todo lo demás no suelen desear más del que tienen. La diversidad de nuestras opiniones no procede de que unos sean más razonables que otros, sino solo de que conducimos nuestros pensamientos por distintas vías y no consideramos las mismas cosas.",
    terminos: ["buen sentido", "opiniones"],
    versiones: [
      { tipo: "rescritura", texto: "Descartes observa, con algo de ironía, que nadie se queja de tener poco buen sentido: todos creemos tener el suficiente. Si pensamos cosas distintas, no es porque unos razonen mejor que otros, sino porque cada uno sigue su propio camino al pensar y se fija en cosas diferentes.",
        porque: "Explica las dos ideas con palabras y frases propias, conserva «buen sentido» y no añade nada que el texto no diga." },
      { tipo: "copia", texto: "El buen sentido es la cosa mejor repartida del mundo, porque cada uno piensa estar bien provisto de él. La diversidad de nuestras opiniones no procede de que unos sean más razonables que otros, sino de que conducimos nuestros pensamientos por distintas vías.",
        porque: "Es un mosaico: pega trozos literales del original y quita algunas palabras. Quitar palabras no es rescribir." },
      { tipo: "sinonimia", texto: "La sensatez es el bien mejor distribuido de la tierra, ya que cada cual cree estar tan bien abastecido de ella que hasta los más exigentes en todo lo restante no acostumbran a querer más de la que poseen. La variedad de nuestros pareceres no viene de que unos sean más sensatos que otros, sino únicamente de que guiamos nuestras ideas por caminos diferentes y no examinamos los mismos asuntos.",
        porque: "Las mismas dos frases, con la misma construcción y en el mismo orden; solo cambian las palabras. Es el original disfrazado." },
      { tipo: "malinterpretacion", texto: "Descartes defiende que todos tenemos la misma inteligencia y que, por tanto, todas las opiniones son igual de válidas: nadie tiene más razón que nadie.",
        porque: "Saca una conclusión que el texto no dice. Que todos tengamos la misma capacidad no significa que todas las opiniones valgan lo mismo: para Descartes, si pensamos distinto es porque no usamos bien la razón, y por eso propone un método." }
    ] },

  { id: "aristoteles", autor: "Aristóteles", obra: "<em>Ética a Nicómaco</em>, libro II (siglo IV a. C.)",
    original: "Las virtudes no se producen en nosotros ni por naturaleza ni contra la naturaleza, sino que nacemos con capacidad para recibirlas y las perfeccionamos mediante la costumbre. Así, practicando la justicia nos hacemos justos; practicando la moderación, moderados, y practicando la valentía, valientes.",
    terminos: ["virtud", "costumbre", "naturaleza"],
    versiones: [
      { tipo: "rescritura", texto: "Según Aristóteles, nadie nace justo o valiente, pero tampoco nace incapaz de llegar a serlo: traemos la capacidad, y la virtud se forma con la costumbre. Uno se vuelve valiente, por ejemplo, a fuerza de actuar con valentía una y otra vez.",
        porque: "Mantiene las dos ideas (la virtud no es innata ni imposible, y se adquiere practicándola) con una construcción propia y un solo ejemplo bien explicado." },
      { tipo: "copia", texto: "Las virtudes no se producen en nosotros ni por naturaleza ni contra la naturaleza: nacemos con capacidad para recibirlas y las perfeccionamos mediante la costumbre. Practicando la justicia nos hacemos justos y practicando la valentía, valientes.",
        porque: "Copia la primera frase casi entera y la segunda a trozos. Cambiar «sino que» por dos puntos no la convierte en tuya." },
      { tipo: "sinonimia", texto: "Las excelencias no se generan en nosotros ni por nacimiento ni en contra del nacimiento, sino que venimos al mundo con aptitud para acogerlas y las completamos por medio del hábito. Así, ejercitando la equidad nos volvemos equitativos; ejercitando la templanza, templados, y ejercitando el coraje, valerosos.",
        porque: "Palabra por palabra, con el mismo esqueleto. Y al cambiar «naturaleza» por «nacimiento» cambia el sentido: Aristóteles habla de la naturaleza humana, no del momento de nacer." },
      { tipo: "malinterpretacion", texto: "Aristóteles piensa que la virtud es algo con lo que se nace: hay personas justas y valientes por naturaleza y otras que nunca lo serán, por mucho que lo intenten.",
        porque: "Afirma justo lo que el texto niega: la virtud no se da por naturaleza, sino que se adquiere con la práctica." }
    ] },

  { id: "rousseau", autor: "Jean-Jacques Rousseau", obra: "<em>Del contrato social</em>, libro I, capítulo 1 (1762)",
    original: "El hombre ha nacido libre y en todas partes está encadenado. Hay quien se cree amo de los demás y no deja de ser más esclavo que ellos. ¿Cómo se ha producido este cambio? Lo ignoro. ¿Qué puede hacerlo legítimo? Creo poder resolver esta cuestión.",
    terminos: ["libre", "legítimo"],
    versiones: [
      { tipo: "rescritura", texto: "Rousseau parte de un contraste: por naturaleza somos libres, pero en la sociedad vivimos sometidos, incluso quienes mandan, que dependen de los demás más que nadie. No pretende explicar cómo se llegó a esa situación; lo que quiere averiguar es qué podría hacer que fuese legítima.",
        porque: "Recoge el contraste, la paradoja del amo y, sobre todo, la diferencia entre las dos preguntas: Rousseau no explica el origen, busca la legitimidad." },
      { tipo: "copia", texto: "El hombre ha nacido libre y en todas partes está encadenado. Quien se cree amo de los demás es más esclavo que ellos. Rousseau no sabe cómo se ha producido este cambio, pero cree poder resolver qué puede hacerlo legítimo.",
        porque: "La primera frase es literal, y el resto, el original con pequeños cambios. Si una frase es famosa, se cita entre comillas; no se hace pasar por propia." },
      { tipo: "sinonimia", texto: "El ser humano ha venido al mundo libre y en todos los lugares se halla atado. Hay quien se considera dueño de los otros y no deja de ser más siervo que ellos. ¿Cómo ha sucedido esta transformación? Lo desconozco. ¿Qué puede volverla justa? Pienso poder solucionar este asunto.",
        porque: "Mismas frases, mismo orden, palabras cambiadas. Y «legítimo» no es lo mismo que «justo»: Rousseau pregunta qué da derecho a mandar." },
      { tipo: "malinterpretacion", texto: "Rousseau explica cómo los hombres perdieron su libertad natural y propone romper las cadenas volviendo a vivir en la naturaleza, sin leyes ni gobierno.",
        porque: "Rousseau dice expresamente que no sabe cómo ocurrió el cambio, y no propone volver a la naturaleza, sino averiguar qué hace legítimo el orden social." }
    ] },

  { id: "hume", autor: "David Hume", obra: "<em>Investigación sobre el entendimiento humano</em>, sección V (1748)",
    original: "La costumbre es, pues, la gran guía de la vida humana. Solo este principio hace que nuestra experiencia nos sea útil y nos lleva a esperar, en el futuro, una serie de acontecimientos semejante a la que ha aparecido en el pasado. Sin la influencia de la costumbre, ignoraríamos por completo toda cuestión de hecho que vaya más allá de lo inmediatamente presente a la memoria y a los sentidos.",
    terminos: ["costumbre", "experiencia", "cuestión de hecho"],
    versiones: [
      { tipo: "rescritura", texto: "Hume sostiene que lo único que nos permite aprovechar la experiencia es la costumbre: como las cosas han ocurrido de cierta manera, esperamos que sigan ocurriendo igual. Sin ese hábito no sabríamos nada de los hechos, salvo lo que estamos viendo o recordando en este momento.",
        porque: "Conserva «costumbre» y «experiencia», explica qué hace la costumbre (nos hace esperar que el futuro se parezca al pasado) y qué pasaría sin ella, con frases propias." },
      { tipo: "copia", texto: "La costumbre es la gran guía de la vida humana: solo este principio hace que nuestra experiencia nos sea útil y nos lleva a esperar en el futuro acontecimientos semejantes a los del pasado. Sin la costumbre ignoraríamos toda cuestión de hecho más allá de lo presente a la memoria y a los sentidos.",
        porque: "Es el original recortado: cada trozo está copiado tal cual." },
      { tipo: "sinonimia", texto: "El hábito es, por tanto, la gran orientadora de la existencia humana. Únicamente esta regla hace que nuestra vivencia nos resulte provechosa y nos conduce a aguardar, en lo venidero, una sucesión de sucesos parecida a la que ha surgido en lo pasado. Sin el efecto del hábito, desconoceríamos completamente cualquier asunto de hecho que vaya más allá de lo directamente presente al recuerdo y a los sentidos.",
        porque: "El mismo texto con otras palabras, frase por frase. Algunas sustituciones, como «orientadora», además suenan forzadas: es una señal típica de sinonimia." },
      { tipo: "malinterpretacion", texto: "Hume demuestra que, gracias a la costumbre, podemos estar seguros de que el futuro será igual que el pasado: la experiencia nos da un conocimiento cierto de lo que va a ocurrir.",
        porque: "Convierte una expectativa en una certeza. Para Hume, la costumbre nos hace <em>esperar</em> que el futuro se parezca al pasado, pero esa espera no se puede demostrar." }
    ] },

  { id: "marx", autor: "Karl Marx", obra: "Prólogo a la <em>Contribución a la crítica de la economía política</em> (1859)",
    original: "El modo de producción de la vida material condiciona el proceso de la vida social, política y espiritual en general. No es la conciencia de los hombres la que determina su ser, sino, por el contrario, su ser social es el que determina su conciencia.",
    terminos: ["modo de producción", "conciencia", "ser social"],
    versiones: [
      { tipo: "rescritura", texto: "Para Marx, la manera en que una sociedad produce lo que necesita para vivir, su modo de producción, marca el resto de su vida: su política, sus leyes y sus ideas. Por eso lo que pensamos depende de las condiciones sociales en que vivimos, y no al revés.",
        porque: "Explica el término técnico en vez de cambiarlo, mantiene la relación de dependencia en el sentido correcto (de la economía a las ideas) y la dice con una construcción propia." },
      { tipo: "copia", texto: "El modo de producción de la vida material condiciona el proceso de la vida social, política y espiritual. No es la conciencia de los hombres la que determina su ser, sino su ser social el que determina su conciencia.",
        porque: "Solo quita «en general» y «por el contrario». Todo lo demás es literal." },
      { tipo: "sinonimia", texto: "La forma de fabricación de la existencia material determina el desarrollo de la existencia social, política y mental en general. No es la mente de las personas la que establece su ser, sino, al contrario, su ser colectivo es el que establece su mente.",
        porque: "Calca la estructura. Y cambia el sentido sin darse cuenta: Marx dice que el modo de producción «condiciona», no que «determina» por completo, y «conciencia» no es lo mismo que «mente»." },
      { tipo: "malinterpretacion", texto: "Marx afirma que las ideas de las personas son las que cambian la sociedad: cuando la gente toma conciencia de la injusticia, transforma la economía.",
        porque: "Invierte la relación. El texto dice que la vida material condiciona las ideas, no que las ideas cambien la economía." }
    ] },

  { id: "mill", autor: "John Stuart Mill", obra: "<em>Sobre la libertad</em>, capítulo I (1859)",
    original: "El único fin por el cual es justificable que la humanidad, individual o colectivamente, se entrometa en la libertad de acción de cualquiera de sus miembros es la propia protección. El único propósito con el que puede ejercerse legítimamente el poder sobre un miembro de una comunidad civilizada, contra su voluntad, es impedir que perjudique a otros. Su propio bien, físico o moral, no es justificación suficiente.",
    terminos: ["libertad", "legítimamente"],
    versiones: [
      { tipo: "rescritura", texto: "Mill pone un solo límite a la libertad de cada persona: los demás, o el Estado, solo pueden obligarla a algo contra su voluntad para evitar que haga daño a otros. Que sea por su propio bien no basta: nadie puede imponerme por la fuerza lo que me conviene a mí.",
        porque: "Recoge las dos partes del principio: cuándo se puede intervenir (para evitar daño a otros) y cuándo no (por el bien del propio individuo)." },
      { tipo: "copia", texto: "El único fin por el cual es justificable entrometerse en la libertad de acción de alguien es la propia protección. El poder solo puede ejercerse legítimamente sobre un miembro de una comunidad civilizada, contra su voluntad, para impedir que perjudique a otros; su propio bien no es justificación suficiente.",
        porque: "Trozos largos copiados literalmente, con pequeños cortes y un punto y coma para unir frases." },
      { tipo: "sinonimia", texto: "La única meta por la que es aceptable que la humanidad, de forma particular o conjunta, se inmiscuya en la libertad de obrar de cualquiera de sus integrantes es la autodefensa. La única intención con la que puede usarse justamente la autoridad sobre un integrante de una sociedad civilizada, contra su deseo, es evitar que dañe a los demás. Su propio beneficio, corporal o moral, no es razón bastante.",
        porque: "Las tres frases del original, en el mismo orden y con sinónimos. «Legítimamente» pasa a «justamente», y no es lo mismo." },
      { tipo: "malinterpretacion", texto: "Mill defiende que cada uno puede hacer lo que quiera, sin ningún límite, y que el Estado nunca debe intervenir en la vida de las personas.",
        porque: "Quita la condición que da sentido al texto: sí hay un límite, el daño a otros, y en ese caso el poder puede intervenir." }
    ] },

  { id: "platon", autor: "Platón", obra: "<em>República</em>, libro VII (siglo IV a. C.)",
    original: "La educación no es lo que algunos proclaman. Dicen que, como no hay ciencia en el alma, ellos la ponen, como quien pone la vista en unos ojos ciegos. Pero lo que ahora decimos muestra que esa capacidad está en el alma de cada uno, y que el órgano con que cada uno aprende debe volverse, con el alma entera, desde lo que deviene hacia lo que es.",
    terminos: ["educación", "alma", "lo que es"],
    versiones: [
      { tipo: "rescritura", texto: "Platón rechaza la idea de que educar sea meter conocimientos en una cabeza vacía, como si se pudiera dar la vista a un ciego. Cada persona ya tiene la capacidad de conocer; educar consiste en orientarla, en hacer que el alma entera deje de mirar lo que cambia y se vuelva hacia lo que es.",
        porque: "Mantiene la crítica, la comparación con la vista y la idea central (educar es girar la mirada), con palabras propias y conservando «alma» y «lo que es»." },
      { tipo: "copia", texto: "La educación no es lo que algunos proclaman: dicen que ponen la ciencia en el alma como quien pone la vista en unos ojos ciegos. Pero esa capacidad está en el alma de cada uno, y el órgano con que se aprende debe volverse con el alma entera hacia lo que es.",
        porque: "Pega fragmentos literales y quita algunos trozos. La metáfora de los ojos ciegos va copiada tal cual." },
      { tipo: "sinonimia", texto: "La enseñanza no es lo que ciertos sostienen. Afirman que, como no hay saber en el espíritu, ellos lo colocan, como quien coloca la visión en unos ojos invidentes. Pero lo que ahora afirmamos indica que esa facultad se halla en el espíritu de cada cual, y que el instrumento con que cada cual comprende debe girarse, con el espíritu entero, desde lo que se genera hacia lo que existe.",
        porque: "Frase a frase, con sinónimos. Y pierde los términos de Platón: «lo que es» no es simplemente «lo que existe», sino lo que es siempre igual, frente a lo que cambia." },
      { tipo: "malinterpretacion", texto: "Platón explica que el maestro debe transmitir al alumno todos los conocimientos que le faltan, igual que un médico cura a un ciego.",
        porque: "Defiende precisamente la idea que Platón critica: para él, el conocimiento no se mete desde fuera." }
    ] },

  { id: "epicuro", autor: "Epicuro", obra: "<em>Carta a Meneceo</em> (siglos IV-III a. C.)",
    original: "Acostúmbrate a pensar que la muerte no es nada para nosotros, porque todo bien y todo mal residen en la sensación, y la muerte es privación de sensación. Así, el más terrible de los males, la muerte, no es nada para nosotros, puesto que mientras nosotros existimos la muerte no está presente, y cuando la muerte está presente, entonces ya no existimos.",
    terminos: ["muerte", "sensación"],
    versiones: [
      { tipo: "rescritura", texto: "Epicuro intenta quitarnos el miedo a morir con un argumento: solo puede hacernos bien o mal lo que sentimos, y muertos no sentimos nada. Además, nunca coincidimos con nuestra muerte: cuando ella llega, nosotros ya no estamos.",
        porque: "Presenta las dos razones del texto con una construcción propia y aclara para qué sirve el argumento (quitar el miedo)." },
      { tipo: "copia", texto: "La muerte no es nada para nosotros, porque todo bien y todo mal residen en la sensación, y la muerte es privación de sensación. Mientras nosotros existimos la muerte no está presente, y cuando la muerte está presente ya no existimos.",
        porque: "Casi literal: solo se quitan el comienzo y algunas palabras." },
      { tipo: "sinonimia", texto: "Habitúate a creer que el fallecimiento no es nada para nosotros, ya que todo beneficio y todo perjuicio se encuentran en la percepción, y el fallecimiento es carencia de percepción. De este modo, el más espantoso de los males, el fallecimiento, no es nada para nosotros, dado que mientras nosotros vivimos el fallecimiento no está presente, y cuando el fallecimiento está presente, entonces ya no vivimos.",
        porque: "El mismo texto con sinónimos y la misma estructura. La repetición de «fallecimiento» donde el original dice «muerte» delata el cambio mecánico." },
      { tipo: "malinterpretacion", texto: "Epicuro dice que no hay que pensar en la muerte y que lo mejor es disfrutar de todos los placeres posibles mientras vivimos, porque después no hay nada.",
        porque: "El texto dice «acostúmbrate a pensar», no «no pienses». Y lo de disfrutar de todos los placeres no está en el fragmento (ni es lo que defiende Epicuro)." }
    ] },

  { id: "hobbes", autor: "Thomas Hobbes", obra: "<em>Leviatán</em>, capítulo 13 (1651). Habla de una situación sin un poder común que imponga el orden.",
    original: "En tal situación no hay lugar para la industria, porque su fruto es incierto; ni, por consiguiente, cultivo de la tierra, ni navegación, ni artes, ni letras, ni sociedad; y, lo que es peor de todo, existe un continuo temor y peligro de muerte violenta; y la vida del hombre es solitaria, pobre, desagradable, brutal y breve.",
    terminos: ["industria"],
    versiones: [
      { tipo: "rescritura", texto: "Hobbes describe cómo sería vivir sin un poder que imponga orden: nadie se molestaría en trabajar, cultivar o crear nada, porque cualquiera podría quitárselo. No habría ciencia, arte ni sociedad, solo miedo constante a morir a manos de otro, y la vida sería corta, aislada y miserable.",
        porque: "Explica la causa (la inseguridad), resume la lista sin copiarla y mantiene la conclusión, con frases propias." },
      { tipo: "copia", texto: "En esa situación no hay lugar para la industria, porque su fruto es incierto, ni cultivo de la tierra, ni navegación, ni artes, ni letras, ni sociedad, sino un continuo temor y peligro de muerte violenta; la vida del hombre es solitaria, pobre, desagradable, brutal y breve.",
        porque: "Prácticamente el original. La famosa lista final, si se usa, va entre comillas." },
      { tipo: "sinonimia", texto: "En semejante estado no hay espacio para el trabajo, ya que su resultado es dudoso; ni, en consecuencia, labranza del suelo, ni navegación, ni oficios, ni literatura, ni comunidad; y, lo que es más grave, hay un miedo constante y riesgo de fallecimiento violento; y la existencia del ser humano es aislada, mísera, molesta, salvaje y corta.",
        porque: "La misma frase, con la misma lista en el mismo orden, y cada palabra sustituida." },
      { tipo: "malinterpretacion", texto: "Hobbes describe la vida de los pueblos primitivos, que eran pobres porque no conocían la agricultura ni la navegación, y dice que el progreso técnico nos ha hecho más felices.",
        porque: "Hobbes no habla de una época de la historia, sino de una situación sin un poder común, y la causa de la miseria es la inseguridad, no la falta de técnica." }
    ] },
  /* (09-10) longitudes de una frase corta a la de un texto de la PAU (200-400 palabras); la vista los ordena por longitud */
  { id: "socrates", autor: "Sócrates (Platón)", obra: "<em>Apología de Sócrates</em>, 38a (siglo IV a. C.)",
    original: "Una vida sin examen no merece ser vivida por el ser humano.",
    terminos: ["examen"],
    versiones: [
      { tipo: "rescritura", texto: "Sócrates sostiene que vivir sin preguntarse nunca por lo que uno hace y piensa no es una vida digna de una persona.",
        porque: "Explica qué significa «examen» (preguntarse por la propia vida) y mantiene la fuerza de la afirmación, con otra construcción." },
      { tipo: "copia", texto: "Para Sócrates, una vida sin examen no merece ser vivida.",
        porque: "Añadir «para Sócrates» delante no basta: el resto es la frase original. Una frase tan conocida se cita entre comillas." },
      { tipo: "sinonimia", texto: "Una existencia sin análisis no es digna de ser vivida por el hombre.",
        porque: "La misma frase con sinónimos. Y «análisis» no es lo mismo que «examen»: Sócrates no habla de analizar datos, sino de revisar la propia vida dialogando." },
      { tipo: "malinterpretacion", texto: "Sócrates dice que solo merece la pena vivir si se aprueban los exámenes y se estudia mucho.",
        porque: "Confunde el examen socrático, que consiste en revisar las propias creencias y acciones, con los exámenes del instituto." }
    ] },

  { id: "protagoras", autor: "Protágoras", obra: "Citado por Platón en el <em>Teeteto</em>, 152a (siglo V a. C.)",
    original: "El hombre es la medida de todas las cosas: de las que son, en cuanto que son, y de las que no son, en cuanto que no son.",
    terminos: ["medida"],
    versiones: [
      { tipo: "rescritura", texto: "Según Protágoras, no hay ningún criterio por encima del ser humano para decidir qué existe y qué no: esa medida la ponemos nosotros.",
        porque: "Conserva la palabra clave, «medida», y explica a qué se aplica (a lo que existe y a lo que no) con una frase propia." },
      { tipo: "copia", texto: "Protágoras dice que el hombre es la medida de todas las cosas, de las que son y de las que no son.",
        porque: "Es la frase original con «Protágoras dice que» delante y un trozo menos." },
      { tipo: "sinonimia", texto: "El ser humano es el criterio de todos los objetos: de los que existen, en tanto que existen, y de los que no existen, en tanto que no existen.",
        porque: "La misma estructura, palabra por palabra. Y «objetos» no recoge lo que dice Protágoras: «todas las cosas» incluye también lo justo, lo bueno o lo verdadero." },
      { tipo: "malinterpretacion", texto: "Protágoras afirma que el ser humano es lo más importante del universo y que todas las demás cosas existen para servirle.",
        porque: "Confunde «medida» con «importancia» o «fin». Protágoras habla del conocimiento (quién decide qué es), no de que el mundo esté hecho para nosotros." }
    ] },

  { id: "nietzsche", autor: "Friedrich Nietzsche", obra: "<em>Sobre verdad y mentira en sentido extramoral</em> (1873)",
    original: "¿Qué es, pues, la verdad? Una hueste en movimiento de metáforas, metonimias, antropomorfismos; en resumen, una suma de relaciones humanas que han sido realzadas, extrapoladas y adornadas poética y retóricamente y que, después de un prolongado uso, a un pueblo le parecen firmes, canónicas y obligatorias. Las verdades son ilusiones de las que se ha olvidado que lo son; metáforas que se han vuelto gastadas y sin fuerza sensible, monedas que han perdido su imagen y ya no se consideran monedas, sino metal.",
    terminos: ["verdad", "metáforas"],
    versiones: [
      { tipo: "rescritura", texto: "Para Nietzsche, lo que llamamos verdades son, en el fondo, creaciones del lenguaje humano: comparaciones, imágenes y proyecciones nuestras que, a fuerza de repetirse durante mucho tiempo, una comunidad acaba aceptando como fijas y obligatorias. Su origen se ha olvidado. Son como metáforas tan usadas que ya no se reconocen como tales, igual que una moneda tan desgastada que ya no muestra su cara y se toma por simple metal.",
        porque: "Recoge las tres ideas (la verdad está hecha de figuras del lenguaje, se impone por el uso y se olvida su origen) y explica la imagen de la moneda, con una construcción propia." },
      { tipo: "copia", texto: "La verdad es una hueste en movimiento de metáforas, metonimias y antropomorfismos, una suma de relaciones humanas realzadas, extrapoladas y adornadas poética y retóricamente que, tras un prolongado uso, a un pueblo le parecen firmes, canónicas y obligatorias. Las verdades son ilusiones de las que se ha olvidado que lo son, monedas que han perdido su imagen y ya no se consideran monedas, sino metal.",
        porque: "Quita la pregunta inicial y una frase, pero todo lo demás está copiado, incluidas las imágenes más personales de Nietzsche." },
      { tipo: "sinonimia", texto: "¿Qué es, entonces, la verdad? Un ejército en marcha de imágenes, figuras, humanizaciones; en suma, un conjunto de vínculos humanos que han sido exaltados, trasladados y embellecidos lírica y oratoriamente y que, tras un largo empleo, a una nación le resultan sólidos, normativos y forzosos. Las verdades son espejismos de los que se ha olvidado que lo son; imágenes que se han quedado desgastadas y sin vigor sensorial, piezas que han perdido su efigie y ya no se tienen por piezas, sino por metal.",
        porque: "Calca el texto frase a frase. Y al cambiar «metáforas» por «imágenes» y «metonimias» por «figuras» se pierde la tesis: para Nietzsche, la verdad está hecha de figuras retóricas concretas." },
      { tipo: "malinterpretacion", texto: "Nietzsche defiende que la verdad no existe y que, por tanto, da igual lo que digamos: todo son mentiras, y mentir no tiene nada de malo.",
        porque: "Exagera y añade. El texto explica el origen de las verdades (metáforas olvidadas); no dice que dé igual lo que digamos ni valora la mentira." }
    ] },

  { id: "cogito", autor: "René Descartes", obra: "<em>Meditaciones metafísicas</em>, segunda meditación (1641)",
    original: "Me he persuadido de que no había nada en absoluto en el mundo: ni cielo, ni tierra, ni espíritus, ni cuerpos. ¿No me he persuadido, entonces, de que yo tampoco existía? Ni mucho menos: si me he persuadido de algo, sin duda yo existía. Pero hay no sé qué engañador, muy poderoso y muy astuto, que emplea toda su habilidad en engañarme siempre. Entonces no hay duda de que yo existo, si me engaña; y que me engañe cuanto quiera: nunca conseguirá que yo no sea nada mientras piense que soy algo. De modo que, después de haberlo pensado bien y de haberlo examinado todo cuidadosamente, hay que concluir y tener por cierto que esta proposición, «yo soy, yo existo», es necesariamente verdadera cada vez que la pronuncio o la concibo en mi espíritu.",
    terminos: ["engañador", "yo soy, yo existo", "espíritu"],
    versiones: [
      { tipo: "rescritura", texto: "Descartes lleva la duda al extremo: supone que no existe nada, ni el mundo ni los cuerpos, e incluso que un ser poderosísimo se dedica a engañarle en todo. Pero descubre que hay algo que resiste a esa duda. Para dudar, para estar convencido de algo o para ser engañado, tiene que existir. Por mucho que el engañador lo intente, no puede conseguir que Descartes deje de existir mientras está pensando. Así llega a su primera certeza: la afirmación «yo soy, yo existo» es verdadera siempre que la piensa.",
        porque: "Sigue el camino del argumento (duda total, engañador, lo que resiste a la duda, conclusión) con frases propias, y cita entre comillas la fórmula, que es un término técnico." },
      { tipo: "copia", texto: "Me he persuadido de que no había nada en el mundo, ni cielo, ni tierra, ni espíritus, ni cuerpos, pero si me he persuadido de algo, sin duda yo existía. Hay un engañador muy poderoso y muy astuto que emplea toda su habilidad en engañarme siempre; entonces no hay duda de que yo existo, si me engaña, y nunca conseguirá que yo no sea nada mientras piense que soy algo. Por eso hay que tener por cierto que la proposición «yo soy, yo existo» es necesariamente verdadera cada vez que la pronuncio o la concibo en mi espíritu.",
        porque: "Un mosaico de frases literales. Hasta conserva la primera persona de Descartes («me he persuadido»), una pista clara de que no está escrito por quien lo explica." },
      { tipo: "sinonimia", texto: "Me he convencido de que no había nada en absoluto en el universo: ni firmamento, ni suelo, ni almas, ni organismos. ¿No me he convencido, por tanto, de que yo tampoco vivía? En absoluto: si me he convencido de algo, sin duda yo vivía. Pero hay no sé qué embaucador, muy potente y muy listo, que utiliza toda su destreza en confundirme siempre. Por tanto no hay duda de que yo vivo, si me confunde; y que me confunda cuanto desee: jamás logrará que yo no sea nada mientras crea que soy algo. De manera que, tras haberlo meditado bien y de haberlo revisado todo atentamente, hay que deducir y considerar seguro que este enunciado, «yo soy, yo vivo», es forzosamente cierto cada vez que lo digo o lo imagino en mi alma.",
        porque: "El mismo texto, frase por frase, con sinónimos. Y estropea los conceptos: «existir» no es «vivir», «pensar» no es «creer» y «concebir» no es «imaginar», porque para Descartes la imaginación es una facultad distinta del pensamiento." },
      { tipo: "malinterpretacion", texto: "Descartes demuestra que todo lo que pensamos es verdad: si pienso algo, ese algo existe. Por eso el mundo existe, porque pienso en él.",
        porque: "Lo único que queda probado es que existe el que piensa, no lo pensado. En este punto, Descartes todavía duda de que exista el mundo." }
    ] },

  { id: "caverna", autor: "Platón", obra: "<em>República</em>, libro VII, 514a-515c (siglo IV a. C.). Hablan Sócrates y Glaucón.",
    original: "—Imagina a unos hombres que viven en una especie de morada subterránea, en forma de caverna, con una larga entrada abierta a la luz que se extiende a lo ancho de toda la caverna. Están en ella desde niños, atados por las piernas y el cuello, de modo que tienen que permanecer en el mismo sitio y mirar solo hacia delante, porque las ataduras les impiden girar la cabeza. Detrás de ellos, en lo alto y a lo lejos, brilla la luz de un fuego, y entre el fuego y los prisioneros hay un camino elevado, a lo largo del cual se ha construido un pequeño muro, parecido a las mamparas que los titiriteros ponen delante del público y por encima de las cuales exhiben sus maravillas.<br>—Me lo imagino.<br>—Imagina ahora que, a lo largo del muro, unos hombres llevan toda clase de objetos que sobresalen por encima de él, figuras de hombres y de animales, de piedra y de madera, y de toda clase de materiales; y, como es natural, unos de los que pasan hablan y otros callan.<br>—Extraña comparación haces, y extraños prisioneros.<br>—Semejantes a nosotros. ¿Crees que han visto de sí mismos o de los otros algo más que las sombras proyectadas por el fuego sobre la pared de la caverna que está frente a ellos?<br>—¿Cómo, si durante toda su vida se ven obligados a tener inmóvil la cabeza?<br>—¿Y no les pasaría lo mismo con los objetos que transportan?<br>—Sin duda.<br>—Entonces, si pudieran hablar entre sí, ¿no crees que tomarían por reales las sombras que ven?<br>—Necesariamente.<br>—Y si la prisión tuviera un eco que viniera de la pared de enfrente, cada vez que hablara alguno de los que pasan, ¿no crees que pensarían que quien habla es la sombra que pasa?<br>—Por Zeus que sí.<br>—Entonces, esos prisioneros no tendrían por verdadero otra cosa que las sombras de los objetos fabricados.",
    terminos: ["caverna", "sombras", "prisioneros"],
    versiones: [
      { tipo: "rescritura", texto: "Platón, por boca de Sócrates, propone imaginar una caverna en la que unos prisioneros llevan encadenados desde la infancia, sin poder moverse ni volver la cabeza, de cara a la pared del fondo. A sus espaldas hay una hoguera; entre ella y los prisioneros, detrás de un muro bajo, unas personas pasean figuras de todo tipo, como en un teatro de marionetas. Los prisioneros solo ven las sombras de esas figuras en la pared; ni siquiera se ven a sí mismos ni a sus compañeros, y oyen el eco de las voces como si salieran de las sombras. Como nunca han visto otra cosa, están convencidos de que esas sombras son la realidad. Y Sócrates añade algo importante: esos prisioneros se parecen a nosotros.",
        porque: "Cuenta la escena completa en el mismo orden lógico, pero con frases propias y sin el diálogo, y no se olvida del detalle decisivo: «semejantes a nosotros»." },
      { tipo: "copia", texto: "Imagina a unos hombres que viven en una morada subterránea en forma de caverna. Están en ella desde niños, atados por las piernas y el cuello, de modo que tienen que permanecer en el mismo sitio y mirar solo hacia delante. Detrás de ellos brilla la luz de un fuego, y entre el fuego y los prisioneros hay un camino elevado con un pequeño muro, parecido a las mamparas de los titiriteros. A lo largo del muro unos hombres llevan toda clase de objetos que sobresalen por encima de él, figuras de hombres y de animales. Los prisioneros no han visto de sí mismos ni de los otros más que las sombras proyectadas por el fuego sobre la pared de la caverna, y tomarían por reales las sombras que ven. Esos prisioneros no tendrían por verdadero otra cosa que las sombras de los objetos fabricados.",
        porque: "Quita el diálogo y une los trozos, pero casi todas las frases están copiadas. Es el caso más frecuente en los exámenes: parece un resumen y es un mosaico." },
      { tipo: "sinonimia", texto: "—Figúrate a unos individuos que habitan en una suerte de vivienda bajo tierra, con forma de cueva, con un amplio acceso abierto a la claridad que se prolonga a lo largo de toda la cueva. Se encuentran en ella desde pequeños, sujetos por las piernas y la nuca, de manera que deben quedarse en el mismo lugar y observar únicamente hacia adelante, ya que las cadenas les impiden volver la cabeza. A sus espaldas, en la altura y a distancia, reluce la claridad de una hoguera, y entre la hoguera y los presos hay una senda alta, a lo largo de la cual se ha levantado una pequeña pared, semejante a las pantallas que los marionetistas colocan ante los espectadores y por encima de las cuales muestran sus prodigios.<br>—Me lo figuro.<br>—Figúrate ahora que, a lo largo de la pared, unos individuos transportan todo tipo de cosas que asoman por encima de ella, imágenes de personas y de bestias, de roca y de leña, y de todo tipo de sustancias; y, como es lógico, algunos de los que pasan conversan y otros guardan silencio.<br>—Rara analogía planteas, y raros presos.<br>—Parecidos a nosotros. ¿Piensas que han contemplado de sí mismos o de los demás algo más que las siluetas arrojadas por la hoguera sobre el muro de la cueva que está ante ellos?<br>—¿Cómo, si a lo largo de toda su existencia se ven forzados a mantener quieta la cabeza?<br>—¿Y no les ocurriría lo mismo con las cosas que acarrean?<br>—Desde luego.<br>—Por tanto, si pudieran conversar entre ellos, ¿no piensas que considerarían verdaderas las siluetas que observan?<br>—Forzosamente.<br>—Y si la cárcel tuviera una resonancia que procediera del muro de enfrente, cada vez que conversara alguno de los que pasan, ¿no piensas que creerían que quien conversa es la silueta que pasa?<br>—Por Zeus que sí.<br>—Por tanto, esos presos no considerarían cierta otra cosa que las siluetas de las cosas elaboradas.",
        porque: "Todo el diálogo, intervención por intervención, con sinónimos. Cuesta tanto como rescribirlo de verdad y no demuestra que se haya entendido. Además, «caverna» y «sombras» son los términos de la alegoría: no hay por qué cambiarlos." },
      { tipo: "malinterpretacion", texto: "Platón cuenta la historia de unos presos reales a los que se castigaba encerrándolos en una cueva, para denunciar lo injustas que eran las cárceles de Atenas. Los guardianes les mostraban sombras para asustarlos, y los presos sabían que eran solo sombras, pero no podían escapar.",
        porque: "Toma la alegoría por un hecho histórico y por una denuncia de las cárceles, y cambia lo esencial: los prisioneros no saben que son sombras, creen que son la realidad. Además, nadie les enseña las sombras para asustarlos." }
    ] },

  { id: "buenavoluntad", autor: "Immanuel Kant", obra: "<em>Fundamentación de la metafísica de las costumbres</em>, capítulo primero (1785)",
    original: "Ni en el mundo ni, en general, fuera de él es posible pensar nada que pueda considerarse bueno sin restricción, a no ser únicamente una buena voluntad. El entendimiento, el ingenio, la capacidad de juzgar, y como quieran llamarse los talentos del espíritu, o el valor, la decisión y la perseverancia en los propósitos, como cualidades del temperamento, son sin duda, en muchos aspectos, buenos y deseables; pero también pueden llegar a ser extraordinariamente malos y dañinos si la voluntad que ha de hacer uso de estos dones de la naturaleza, y cuya constitución particular se llama por eso carácter, no es buena. Lo mismo sucede con los dones de la fortuna. El poder, la riqueza, el honor, incluso la salud y todo el bienestar y la satisfacción con el propio estado, bajo el nombre de felicidad, dan valor y a menudo también arrogancia si no hay una buena voluntad que corrija y oriente hacia fines universales su influjo sobre el ánimo. […] La buena voluntad no es buena por lo que realiza o consigue, ni por su aptitud para alcanzar algún fin propuesto, sino solo por el querer; es decir, es buena en sí misma. Considerada por sí misma, hay que estimarla sin comparación muy por encima de todo lo que por medio de ella pudiera conseguirse en favor de alguna inclinación, o incluso de la suma de todas las inclinaciones. Aunque, por una particular desgracia del destino o por la mezquindad de una naturaleza madrastra, le faltase por completo a esta voluntad la capacidad de sacar adelante su propósito; aunque con su mayor esfuerzo no consiguiera nada y solo quedase la buena voluntad, no como un mero deseo, sino como el empleo de todos los medios que están en nuestro poder, brillaría por sí misma como una joya, como algo que tiene en sí mismo su pleno valor. La utilidad o la inutilidad no pueden añadir ni quitar nada a ese valor.",
    terminos: ["buena voluntad", "carácter", "felicidad", "inclinación", "inclinaciones"],
    versiones: [
      { tipo: "rescritura", texto: "Kant empieza buscando algo que sea bueno sin condiciones, y concluye que solo lo es la buena voluntad. Todo lo demás que solemos valorar es bueno solo a medias. Las capacidades intelectuales, como la inteligencia o el ingenio, y las del carácter, como el valor o la constancia, son útiles muchas veces, pero en manos de una mala voluntad pueden hacer mucho daño. Lo mismo pasa con lo que nos da la suerte, como el poder, el dinero, la fama o la salud, y que, juntos, Kant llama felicidad: sin una buena voluntad que los oriente, pueden volver a una persona soberbia. Además, el valor de la buena voluntad no depende de sus resultados, sino del querer mismo. Aunque, por mala suerte, alguien que quiere hacer el bien y pone todos los medios a su alcance no lograra nada, su voluntad seguiría valiendo lo mismo: sería como una joya que brilla con luz propia. Que sea útil o inútil no le añade ni le quita valor.",
        porque: "Ordena el texto en sus pasos (lo único bueno sin condiciones, los talentos, los dones de la fortuna, el valor independiente del resultado) con palabras propias. Conserva «buena voluntad», «carácter» y «felicidad», y la imagen de la joya, que es esencial." },
      { tipo: "copia", texto: "No es posible pensar nada que pueda considerarse bueno sin restricción, a no ser únicamente una buena voluntad. El entendimiento, el ingenio y la capacidad de juzgar, o el valor, la decisión y la perseverancia, son sin duda buenos y deseables, pero también pueden llegar a ser extraordinariamente malos y dañinos si la voluntad que ha de hacer uso de estos dones no es buena. Lo mismo sucede con los dones de la fortuna: el poder, la riqueza, el honor y la salud dan valor y a menudo también arrogancia si no hay una buena voluntad. La buena voluntad no es buena por lo que realiza o consigue, sino solo por el querer; es decir, es buena en sí misma. Aunque con su mayor esfuerzo no consiguiera nada, brillaría por sí misma como una joya, como algo que tiene en sí mismo su pleno valor.",
        porque: "Selecciona bien las ideas, pero cada frase está sacada del original. Elegir qué copiar no es lo mismo que explicar: en la PAU puntúa la comprensión, y aquí no se ve." },
      { tipo: "sinonimia", texto: "Ni en el universo ni, en general, fuera de él es factible concebir nada que pueda estimarse bueno sin límite, salvo exclusivamente una recta intención. La inteligencia, el talento, la facultad de discernir, y como quieran denominarse las aptitudes de la mente, o el coraje, la resolución y la constancia en los fines, como rasgos del genio, son sin duda, en numerosos sentidos, buenos y apetecibles; pero también pueden llegar a ser enormemente perversos y perjudiciales si la intención que ha de servirse de estos regalos de la naturaleza, y cuya composición propia se denomina por ello temperamento, no es recta. Lo mismo ocurre con los regalos de la suerte. La autoridad, el dinero, la honra, incluso la salud y todo el confort y el contento con la propia situación, bajo el nombre de dicha, dan ánimo y con frecuencia también soberbia si no hay una recta intención que enderece y encamine hacia metas universales su efecto sobre el espíritu. […] La recta intención no es buena por lo que efectúa o logra, ni por su idoneidad para conseguir alguna meta planteada, sino únicamente por el desear; o sea, es buena en sí misma. Contemplada por sí misma, hay que valorarla sin comparación muy por encima de todo lo que mediante ella pudiera lograrse en beneficio de alguna tendencia, o incluso de la suma de todas las tendencias. Aunque, por una especial desdicha del destino o por la tacañería de una naturaleza hostil, le faltase completamente a esta intención la facultad de llevar a cabo su objetivo; aunque con su máximo empeño no lograra nada y solo quedase la recta intención, no como un simple anhelo, sino como el uso de todos los recursos que están a nuestro alcance, resplandecería por sí misma como una alhaja, como algo que tiene en sí mismo su completo valor. El provecho o la falta de provecho no pueden agregar ni restar nada a ese valor.",
        porque: "Trescientas setenta palabras cambiadas una a una, con el mismo esqueleto. Y desfigura a Kant: «buena voluntad» no es una «recta intención» (Kant advierte que no es un mero deseo), «carácter» no es «temperamento» y «felicidad» no es «dicha»." },
      { tipo: "malinterpretacion", texto: "Kant sostiene que lo único que importa son las buenas intenciones: basta con querer hacer el bien, aunque no se haga nada para conseguirlo. Por eso la inteligencia, el valor, la riqueza o la salud no tienen ningún valor y son malos en sí mismos, y una persona buena debería renunciar a ellos.",
        porque: "Exagera en dos sentidos. Kant no habla de un mero deseo, sino de una voluntad que pone «todos los medios que están en nuestro poder». Y no dice que los talentos o la felicidad sean malos: dice que son buenos en muchos aspectos, pero no sin condiciones." }
    ] },
  /* (09-10) escalón intermedio entre los 134 y los 320 (unas 230 palabras) */
  { id: "politica", autor: "Aristóteles", obra: "<em>Política</em>, libro I, capítulo 2 (siglo IV a. C.)",
    original: "De todo esto resulta evidente que la ciudad es una de las cosas que existen por naturaleza, y que el hombre es por naturaleza un animal político. Y quien por naturaleza, y no por azar, vive fuera de la ciudad es o un ser inferior o un ser superior al hombre. La razón por la que el hombre es un animal político en mayor grado que cualquier abeja o cualquier animal gregario es clara: la naturaleza, como decimos, no hace nada en vano, y el hombre es el único animal que tiene palabra. La voz es signo del dolor y del placer, y por eso la tienen también los demás animales, pues su naturaleza llega hasta tener sensación del dolor y del placer y comunicárselas unos a otros. Pero la palabra existe para manifestar lo conveniente y lo dañino, y también lo justo y lo injusto. Y esto es lo propio del hombre frente a los demás animales: ser el único que tiene la percepción del bien y del mal, de lo justo y de lo injusto, y de las demás cosas de este tipo. La comunidad de estas cosas es lo que constituye la casa y la ciudad. Quien no puede vivir en comunidad, o no necesita nada porque se basta a sí mismo, no es miembro de la ciudad, sino una bestia o un dios.",
    terminos: ["ciudad", "animal político", "palabra", "naturaleza"],
    versiones: [
      { tipo: "rescritura", texto: "Para Aristóteles, vivir en una ciudad no es un invento ni un acuerdo, sino algo propio de la naturaleza humana: somos animales políticos. Lo somos más que las abejas o que cualquier animal que vive en grupo, y la prueba es que solo nosotros tenemos palabra. Los demás animales tienen voz, que les basta para expresar y compartir lo que les hace sufrir o disfrutar. La palabra, en cambio, sirve para algo más: decir qué nos conviene y qué nos perjudica, qué es justo y qué es injusto. Como la naturaleza no da nada sin un fin, si nos ha dado la palabra es para que compartamos esa idea del bien y de la justicia, y eso es lo que da origen a la familia y a la ciudad. Por eso, quien de verdad no puede vivir con otros, o no los necesita para nada, está por debajo de lo humano, como una bestia, o por encima, como un dios.",
        porque: "Sigue el argumento completo (la ciudad es natural, la prueba de la palabra, la diferencia entre voz y palabra, la conclusión) en otro orden y con frases propias, y conserva los términos «animal político», «palabra» y «ciudad»." },
      { tipo: "copia", texto: "La ciudad es una de las cosas que existen por naturaleza, y el hombre es por naturaleza un animal político, en mayor grado que cualquier abeja o cualquier animal gregario, porque la naturaleza no hace nada en vano y el hombre es el único animal que tiene palabra. La voz es signo del dolor y del placer, y por eso la tienen también los demás animales; pero la palabra existe para manifestar lo conveniente y lo dañino, y también lo justo y lo injusto. La comunidad de estas cosas es lo que constituye la casa y la ciudad. Quien no puede vivir en comunidad no es miembro de la ciudad, sino una bestia o un dios.",
        porque: "Une con comas frases enteras del original y se salta las demás. Parece un buen resumen, pero no hay ni una frase propia." },
      { tipo: "sinonimia", texto: "De todo lo anterior se deduce con claridad que la polis es una de las realidades que se dan por esencia, y que el ser humano es por esencia un ser social. Y quien por esencia, y no por casualidad, habita fuera de la polis es o un ente inferior o un ente superior al ser humano. El motivo por el que el ser humano es un ser social en mayor medida que cualquier abeja o cualquier bestia de rebaño es evidente: la esencia, como afirmamos, no hace nada inútilmente, y el ser humano es el único ser vivo que posee lenguaje. El sonido es señal del sufrimiento y del gozo, y por ello lo poseen también los restantes seres vivos, ya que su esencia alcanza hasta tener percepción del sufrimiento y del gozo y transmitírselas unos a otros. Pero el lenguaje existe para expresar lo provechoso y lo perjudicial, y también lo equitativo y lo inicuo. Y esto es lo característico del ser humano frente a los restantes seres vivos: ser el único que posee la noción del bien y del mal, de lo equitativo y de lo inicuo, y de las restantes cuestiones de esta clase. La participación en estas cuestiones es lo que forma el hogar y la polis. Quien no puede habitar en sociedad, o no precisa nada porque es autosuficiente, no es integrante de la polis, sino una fiera o una divinidad.",
        porque: "El mismo texto, frase a frase, con sinónimos. Y estropea los conceptos clave: «animal político» no es «ser social» (las abejas también son sociales; lo político exige palabra y justicia), «naturaleza» no es «esencia» y «palabra» no es cualquier «lenguaje»." },
      { tipo: "malinterpretacion", texto: "Aristóteles sostiene que los seres humanos somos como las abejas: vivimos en sociedad por instinto, igual que cualquier animal gregario. Por eso quien vive solo, como un ermitaño, es un ser superior, casi un dios, porque ha conseguido liberarse de ese instinto.",
        porque: "Dice dos cosas que el texto niega. Aristóteles distingue al ser humano de las abejas precisamente por la palabra y el sentido de la justicia, no lo iguala con ellas. Y quien vive fuera de la ciudad por naturaleza es «una bestia o un dios», no alguien admirable por haberse liberado." }
    ] },
  /* (09-10) escalón entre los 83 y los 134 (unas 120 palabras); en francés, el texto original de Montaigne */
  { id: "canibales", autor: "Michel de Montaigne", obra: "<em>Ensayos</em>, libro I, capítulo 31, «De los caníbales» (1580). Habla de los pueblos indígenas de Brasil.",
    original: "Me parece que no hay nada bárbaro ni salvaje en esa nación, según lo que me han contado, sino que cada cual llama barbarie a lo que no es de su costumbre. Parece, en verdad, que no tenemos otra medida de la verdad y de la razón que el ejemplo y la idea de las opiniones y usos del país en que vivimos: allí está siempre la religión perfecta, el gobierno perfecto, el uso perfecto y acabado de todas las cosas. Son salvajes del mismo modo que llamamos salvajes a los frutos que la naturaleza ha producido por sí misma y en su curso ordinario; cuando, en verdad, a los que hemos alterado con nuestro artificio y desviado del orden común es a los que más bien deberíamos llamar salvajes.",
    terminos: ["bárbaro", "barbarie", "salvaje", "naturaleza"],
    versiones: [
      { tipo: "rescritura", texto: "Montaigne sospecha que, cuando llamamos bárbaros a otros pueblos, solo estamos diciendo que no viven como nosotros. Tomamos las costumbres y creencias de nuestro propio país como patrón de lo verdadero y lo razonable, y por eso nuestra religión, nuestras leyes y nuestras maneras nos parecen siempre las mejores. Juega además con la palabra «salvaje»: si salvaje es lo que crece por sí solo, como la fruta del campo, esos pueblos lo son en el buen sentido; lo que de verdad se ha apartado de la naturaleza, y habría que llamar salvaje, es lo que nosotros hemos deformado con nuestro artificio.",
        porque: "Explica las dos ideas (juzgamos a los demás con la vara de nuestras costumbres; el doble sentido de «salvaje») con frases propias, y hace explícito el juego de palabras, que es la clave del texto." },
      { tipo: "copia", texto: "En esa nación no hay nada bárbaro ni salvaje, sino que cada cual llama barbarie a lo que no es de su costumbre. No tenemos otra medida de la verdad y de la razón que el ejemplo y la idea de las opiniones y usos del país en que vivimos: allí está siempre la religión perfecta, el gobierno perfecto. Son salvajes del mismo modo que llamamos salvajes a los frutos que la naturaleza ha producido por sí misma, cuando a los que hemos alterado con nuestro artificio es a los que deberíamos llamar salvajes.",
        porque: "El original con algunos cortes. La frase más famosa, «cada cual llama barbarie a lo que no es de su costumbre», se puede usar, pero entre comillas." },
      { tipo: "sinonimia", texto: "Me da la impresión de que no hay nada incivilizado ni primitivo en ese pueblo, según lo que me han relatado, sino que cada uno llama incivilización a lo que no es de su hábito. Da la impresión, realmente, de que no tenemos otro criterio de lo cierto y de lo sensato que la muestra y la noción de los pareceres y prácticas de la tierra en que residimos: ahí está siempre la fe perfecta, la administración perfecta, la práctica perfecta y completa de todos los asuntos. Son primitivos de la misma manera que llamamos primitivos a los productos que el entorno ha generado por sí mismo y en su marcha habitual; cuando, realmente, a los que hemos modificado con nuestra técnica y apartado del orden general es a los que más bien tendríamos que llamar primitivos.",
        porque: "Calca el texto frase a frase. Y rompe el juego de palabras que sostiene el argumento: Montaigne usa «salvaje» en dos sentidos (sin civilizar y silvestre, como la fruta), y «primitivo» no tiene el segundo. Además, «naturaleza» no es «entorno»." },
      { tipo: "malinterpretacion", texto: "Montaigne defiende que los pueblos indígenas de América eran superiores a los europeos en todo y que lo mejor sería abandonar la civilización y volver a vivir como ellos, en plena naturaleza.",
        porque: "Exagera y añade. El texto critica que juzguemos a los demás con la vara de nuestras costumbres y le da la vuelta a la palabra «salvaje»; no dice que esos pueblos sean superiores en todo ni que haya que abandonar la civilización." }
    ] }
];
